import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import { compileFighterContent } from '../src/content/fighter.js';
import { initialFighterState, fighterWorldHash } from '../src/sim/fighter-state.js';
import { FighterSimulation } from '../src/sim/fighter.js';
import { effective } from '../src/sim/abilities/effective.js';
import { sweepCircles } from '../src/math/geometry.js';
import { moveBodies } from '../src/sim/physics/motion.js';
import { NEUTRAL_INTENT, type ActionIntent } from '../src/contracts/state.js';
import type { FighterConfig, FighterWorld, BattleEvent } from '../src/contracts/fighter.js';
import type { ContentSource } from '../src/contracts/content-schema.js';
const source = JSON.parse(readFileSync('content/fighter-phase1.json', 'utf8')) as ContentSource;
const content = compileFighterContent(source);
export function config(a = 'standard', b = 'rubber', maxTicks = 3600): FighterConfig { return { matchId: 'test', seed: 17, rulesetId: 'fighter', rulesetVersion: 1, arenaId: content.source.arenas[0]!.id, contentHash: content.bundleHash, pacing: { mode: 'off', profileId: null }, participants: [{ participantId: 'A', characterId: a, profileId: a === 'rubber' ? 'pressure' : 'balanced' }, { participantId: 'B', characterId: b, profileId: b === 'rubber' ? 'pressure' : 'balanced' }], maxTicks }; }
function scenario(a = 'standard', b = 'rubber', edit: (w: FighterWorld) => void = () => { }, custom = content) { const c = { ...config(a, b), contentHash: custom.bundleHash }; const w = JSON.parse(JSON.stringify(initialFighterState(c, custom))) as FighterWorld; edit(w); return new FighterSimulation(custom, c, w); }
const cast = (slot: 'basic' | 'skill1' | 'skill2' | 'ultimate', requestId = 1, aimX: 1 | -1 = 1): ActionIntent => ({ moveX: 0, jumpPressed: false, cast: { slot, aimX }, requestId });
const advance = (sim: FighterSimulation, n: number): BattleEvent[] => Array.from({ length: n }, () => sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).events).flat();
describe('continuous physics and action protocol', () => {
    it('boundary contact budget diagnoses and stops the remaining displacement', () => { const w = JSON.parse(JSON.stringify(initialFighterState(config('standard', 'standard'), content))) as FighterWorld; w.entities[0].body.position = { x: 32.05, y: 200 }; w.entities[1].body.position = { x: 32.05, y: 500 }; w.entities[0].body.velocity.x = 1800; for (const e of w.entities)
        e.body.grounded = false; const materials = w.entities.map(e => ({ ...effective(e, content, 0), restitution: 1 })) as [
        ReturnType<typeof effective>,
        ReturnType<typeof effective>
    ]; const diagnostics: string[] = []; let bounces = 0; const paths = moveBodies(w.entities, materials, [null, null], { width: 64.1, height: 960, gravity: { x: 0, y: 0 } }, 1 / 240, () => bounces++, (code) => diagnostics.push(code)); expect(bounces).toBe(4); expect(diagnostics).toEqual(['BOUNDARY_CONTACT_LIMIT']); expect(paths[0].at(-1)!.from).toEqual(paths[0].at(-1)!.to); expect(paths[0].at(-1)!.end).toBe(1); });
    it('relative sweep catches moving targets and rejects a miss', () => { expect(sweepCircles({ x: 0, y: 0 }, { x: 100, y: 0 }, 8, { x: 150, y: 0 }, { x: 50, y: 0 }, 24)).toBeCloseTo(.59); expect(sweepCircles({ x: 0, y: 100 }, { x: 100, y: 100 }, 8, { x: 150, y: 0 }, { x: 50, y: 0 }, 24)).toBeNull(); });
    it('starts radius-aware, rests without bounce spam and jumps under gravity', () => { const sim = scenario(); expect(sim.snapshot().entities[0].body.position.y).toBe(32); expect(advance(sim, 60).some(e => e.type === 'WallBounce')).toBe(false); sim.step([{ ...NEUTRAL_INTENT, jumpPressed: true, requestId: 1 }, NEUTRAL_INTENT]); expect(sim.snapshot().entities[0].body.velocity.y).toBeCloseTo(595); expect(sim.snapshot().entities[0].body.position.y).toBeGreaterThan(32); advance(sim, 150); expect(sim.snapshot().entities[0].body.grounded).toBe(true); });
    it('high-speed opposing bodies collide without tunneling; full overlap separates stably', () => {
        const sim = scenario('standard', 'standard', w => {
            w.entities[0].body.position = { x: 400, y: 300 };
            w.entities[1].body.position = { x: 470, y: 300 };
            for (const e of w.entities)
                e.body.grounded = false;
            w.entities[0].body.velocity.x = 1800;
            w.entities[1].body.velocity.x = -1800;
        });
        sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]);
        expect(sim.snapshot().entities[0].body.velocity.x).toBeLessThan(0);
        expect(sim.snapshot().entities[1].body.velocity.x).toBeGreaterThan(0);
        expect(sim.snapshot().entities[1].body.position.x - sim.snapshot().entities[0].body.position.x).toBeGreaterThanOrEqual(64);
        const same = scenario('standard', 'standard', w => {
            for (const e of w.entities)
                e.body.position = { x: 480, y: 32 };
        });
        same.step([NEUTRAL_INTENT, NEUTRAL_INTENT]);
        expect(same.snapshot().entities[0].body.position.x).toBeLessThan(same.snapshot().entities[1].body.position.x);
    });
    it('request retries accept once, cast wins jump conflict, finished receipt survives', () => { const sim = scenario(); const first = sim.step([{ ...cast('basic'), jumpPressed: true }, NEUTRAL_INTENT]); expect(first.receipts.map(r => r.result)).toEqual(['accepted', 'rejected']); expect(first.receipts[1]!.reason).toBe('conflict'); expect(sim.step([cast('basic'), NEUTRAL_INTENT]).receipts[0]!.reason).toBe('duplicate'); advance(sim, 24); expect(sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).receipts.some(r => r.result === 'finished')).toBe(true); });
    it('wall reflects only normal velocity and floor low-speed landing is quiet', () => { const sim = scenario('standard', 'standard', w => { const e = w.entities[0]; e.body.position = { x: 33, y: 300 }; e.body.velocity = { x: -900, y: 200 }; e.body.grounded = false; }); const r = sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(r.events.filter(e => e.type === 'WallBounce')).toHaveLength(1); expect(r.state.entities[0].body.velocity.x).toBeGreaterThan(500); expect(r.state.entities[0].body.velocity.y).toBeCloseTo(175); });
});
describe('combat, scheduler, status and restoration', () => {
    it('dash sets horizontal speed to 900 during active frames and removes its hitbox at the half-open boundary', () => { const sim = scenario('rubber', 'standard', w => { w.entities[0].body.velocity.x = 320; }); sim.step([cast('skill1'), NEUTRAL_INTENT]); advance(sim, 8); expect(sim.snapshot().entities[0].body.velocity.x).toBe(900); expect(sim.snapshot().hitboxes).toHaveLength(1); advance(sim, 9); expect(sim.snapshot().tick).toBe(18); sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(sim.snapshot().hitboxes).toHaveLength(0); });
    it('standard volley emits at 18/30/42 with separate hit groups; push executes its declared launch', () => { const volley = scenario('standard', 'standard', w => { w.entities[0].energy = 100; }); volley.step([cast('ultimate'), NEUTRAL_INTENT]); const emissions = advance(volley, 42).filter(e => e.type === 'ProjectileSpawned'); expect(emissions.map(e => e.tick)).toEqual([18, 30, 42]); const push = scenario('standard', 'standard', w => { w.entities[0].body.position.x = 400; w.entities[1].body.position.x = 466; }); push.step([cast('skill2'), NEUTRAL_INTENT]); advance(push, 16); expect(push.snapshot().entities[1].hp).toBe(92); expect(push.snapshot().entities[1].body.velocity.x).toBeCloseTo(850); });
    it('overkill contributes only actual damage to outgoing energy; dead targets earn no energy', () => { const sim = scenario('standard', 'standard', w => { w.entities[0].body.position.x = 400; w.entities[1].body.position.x = 466; w.entities[1].hp = 3; }); sim.step([cast('basic'), NEUTRAL_INTENT]); const ev = advance(sim, 8).find(e => e.type === 'DamageResolved'); expect(ev?.type === 'DamageResolved' ? ev.payload.amount : null).toBe(3); expect(sim.snapshot().entities[0].energy).toBeCloseTo(3 * .35 + 9 / 60); expect(sim.snapshot().entities[1].energy).toBeCloseTo(8 / 60); });
    it('overdrive changes the wall growth coefficient, clamps stacks at three and honors six-tick cooldown', () => { const sim = scenario('rubber', 'standard', w => { w.entities[0].statuses = [{ instanceId: 1, definitionId: 'overdrive', sourceId: 1, sourceCastId: null, appliedTick: 0, expiresTick: 240, stacks: 1 }]; }); const wall = () => { const w = JSON.parse(JSON.stringify(sim.snapshot())) as FighterWorld; w.entities[0].body.position = { x: 33, y: 500 }; w.entities[0].body.velocity = { x: -900, y: 0 }; w.entities[0].body.grounded = false; sim.restore(w); return sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); }; wall(); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(1); expect(sim.snapshot().entities[0].body.velocity.x).toBeGreaterThan(888); expect(wall().events.filter(e => e.type === 'PassiveTriggered')).toHaveLength(0); advance(sim, 4); wall(); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(2); advance(sim, 5); wall(); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(3); advance(sim, 5); wall(); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(3); });
    it('rubber floor impact never triggers wall growth; corner contacts are finite and bounded', () => { const floor = scenario('rubber', 'standard', w => { const e = w.entities[0]; e.body.position.y = 33; e.body.velocity.y = -900; e.body.grounded = false; }); const f = floor.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(f.events.some(e => e.type === 'WallBounce')).toBe(true); expect(f.events.some(e => e.type === 'PassiveTriggered')).toBe(false); const corner = scenario('rubber', 'standard', w => { const e = w.entities[0]; e.body.position = { x: 33, y: 927 }; e.body.velocity = { x: -1200, y: 1200 }; e.body.grounded = false; }); const out = corner.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(out.state.result).toBeNull(); expect(out.events.filter(e => e.type === 'WallBounce')).toHaveLength(2); expect(out.state.entities[0].body.position.x).toBeGreaterThanOrEqual(32); expect(out.state.entities[0].body.position.y).toBeLessThanOrEqual(928); });
    it('resource limits diagnose the match and preserve the last finite state rather than dropping effects', () => { const src = structuredClone(source), a = src.abilities.find(a => a.id === 'standard-bolt')!, effect = a.timeline[0]!.effects[0]!; a.timeline = [{ offsetTick: 12, effects: Array.from({ length: 32 }, () => structuredClone(effect)) }, { offsetTick: 12, effects: [structuredClone(effect)] }]; const custom = compileFighterContent(src), sim = scenario('standard', 'standard', () => { }, custom); sim.step([cast('skill1'), NEUTRAL_INTENT]); const out = advance(sim, 12); expect(sim.snapshot().result?.reason).toBe('invalid'); expect(sim.snapshot().diagnostics[0]!.detail).toMatch(/budget/); expect(out.filter(e => e.type === 'Diagnostic')).toHaveLength(1); expect(sim.snapshot().projectiles).toHaveLength(0); });
    it('same tick lethal trades resolve both hits and dedupe active hitboxes', () => {
        const sim = scenario('standard', 'standard', w => {
            w.entities[0].body.position.x = 400;
            w.entities[1].body.position.x = 466;
            for (const e of w.entities)
                e.hp = 8;
        });
        sim.step([cast('basic'), cast('basic', 1, -1)]);
        const ev = advance(sim, 8);
        expect(sim.snapshot().result?.reason).toBe('double-ko');
        expect(ev.filter(e => e.type === 'DamageResolved')).toHaveLength(2);
    });
    it('one hit per cast/group despite multiple substeps and active ticks; damage energy uses actual HP', () => { const sim = scenario('standard', 'standard', w => { w.entities[0].body.position.x = 400; w.entities[1].body.position.x = 466; }); sim.step([cast('basic'), NEUTRAL_INTENT]); const ev = advance(sim, 14); expect(ev.filter(e => e.type === 'DamageResolved')).toHaveLength(1); expect(sim.snapshot().entities[1].hp).toBe(92); expect(sim.snapshot().entities[0].energy).toBeCloseTo(2.8 + 15 / 60); expect(sim.snapshot().entities[1].energy).toBeCloseTo(4.4 + 15 / 60); });
    it('zero startup emits immediately and accepted request is not cached on cooldown', () => { const src = structuredClone(source); const a = src.abilities.find(a => a.id === 'standard-jab')!; a.startupTicks = 0; a.timeline[0]!.offsetTick = 0; const bundle = compileFighterContent(src); const sim = scenario('standard', 'standard', w => { w.entities[0].body.position.x = 400; w.entities[1].body.position.x = 466; }, bundle); expect(sim.step([cast('basic'), NEUTRAL_INTENT]).events.some(e => e.type === 'HitResolved')).toBe(true); });
    it('volley cancels before first shot, survives interruption after first shot', () => {
        const make = (tick: number) => scenario('standard', 'standard', w => { w.tick = tick; const e = w.entities[0]; e.energy = 100; e.action = { kind: 'cast', castId: 1, requestId: 1, abilityId: 'standard-volley', startedTick: 0, startupTicks: 18, activeTicks: 1, recoveryTicks: 24 }; w.casts = [{ castId: 1, rootEventSeq: 1, ownerId: 1, requestId: 1, abilityId: 'standard-volley', aimX: 1, startedTick: 0, endsTick: 43, firstEmissionTick: tick > 18 ? 18 : null, interruptedTick: null, finishedTick: null, scheduledPolicy: 'before-first-emission' }]; w.scheduledEffects = content.source.abilities.find(a => a.id === 'standard-volley')!.timeline.filter(s => s.offsetTick >= tick).map((s, i) => ({ id: i + 1, dueTick: s.offsetTick, ownerId: 1, castId: 1, effects: structuredClone(s.effects) as never })); w.nextCastId = 3; w.projectiles = [{ id: 3, ownerId: 2, sourceCastId: 2, abilityId: 'standard-bolt', position: { x: e.body.position.x + 42, y: 32 }, velocity: { x: -720, y: 0 }, radius: 12, expiresTick: 100, reflectionCount: 0, ignoreOwnerUntilOutside: false, hit: { damage: 1, launchDeltaV: { x: 0, y: 0 }, hitstunTicks: 10, hitGroup: 'bolt' } }]; });
        const early = make(10);
        early.step([NEUTRAL_INTENT, NEUTRAL_INTENT]);
        expect(early.snapshot().scheduledEffects).toHaveLength(0);
        const late = make(20);
        late.step([NEUTRAL_INTENT, NEUTRAL_INTENT]);
        expect(late.snapshot().scheduledEffects).toHaveLength(2);
        expect(advance(late, 23).filter(e => e.type === 'ProjectileSpawned' && e.sourceId === 1)).toHaveLength(2);
    });
    it('cushion reduces damage but amplifies launch, and modifiers revert exactly on expiry', () => { const sim = scenario('rubber', 'standard', w => { w.entities[0].body.position.x = 400; w.entities[1].body.position.x = 466; }); sim.step([cast('skill2'), NEUTRAL_INTENT]); advance(sim, 5); expect(effective(sim.snapshot().entities[0], content, 6).damageTaken).toBe(.6); sim.step([NEUTRAL_INTENT, cast('basic', 1, -1)]); advance(sim, 8); expect(sim.snapshot().entities[0].hp).toBe(95.2); expect(sim.snapshot().entities[0].body.velocity.x).toBeLessThan(-700); advance(sim, 30); expect(effective(sim.snapshot().entities[0], content, sim.snapshot().tick).damageTaken).toBe(1); });
    it('rubber wall growth excludes floor, stacks up to three, overrides growth during overdrive', () => { const sim = scenario('rubber', 'standard', w => { const e = w.entities[0]; e.body.position = { x: 33, y: 300 }; e.body.grounded = false; e.body.velocity = { x: -900, y: 0 }; }); const r = sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(r.events.some(e => e.type === 'PassiveTriggered')).toBe(true); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(1); expect(sim.snapshot().entities[0].body.velocity.x).toBeGreaterThan(830); const stopped = JSON.parse(JSON.stringify(sim.snapshot())) as FighterWorld; stopped.entities[0].body.velocity = { x: 0, y: 0 }; sim.restore(stopped); advance(sim, 120); expect(sim.snapshot().passiveRuntime[0]!.stacks).toBe(0); });
    it('ultimate spends 100 and suppresses ALL energy growth for 240 ticks', () => { const sim = scenario('rubber', 'standard', w => { w.entities[0].energy = 100; }); sim.step([cast('ultimate'), NEUTRAL_INTENT]); advance(sim, 239); expect(sim.snapshot().entities[0].energy).toBe(0); sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(sim.snapshot().entities[0].energy).toBeCloseTo(1 / 60); });
    it('restore includes pending effects, dedupe registry and IDs; nonfinite inputs yield diagnostics', () => { const sim = scenario(); sim.step([cast('skill1'), NEUTRAL_INTENT]); advance(sim, 5); const snap = sim.snapshot(); const restored = new FighterSimulation(content, config(), snap); advance(sim, 100); advance(restored, 100); expect(fighterWorldHash(restored.snapshot())).toBe(fighterWorldHash(sim.snapshot())); const bad = restored.step([{ ...NEUTRAL_INTENT, moveX: NaN } as never, NEUTRAL_INTENT]); expect(bad.state.result?.reason).toBe('invalid'); expect(bad.events[0]!.type).toBe('Diagnostic'); });
    it('timeout is deterministic at the normalized HP tolerance boundary', () => { const c = { ...config('standard', 'rubber', 1) }; const w = JSON.parse(JSON.stringify(initialFighterState(c, content))) as FighterWorld; w.entities[0].hp = 99.5; const sim = new FighterSimulation(content, c, w); expect(sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).state.result?.winnerParticipantId).toBeNull(); });
});
