import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import { compilePhase3BContent } from '../src/content/phase3b.js';
import { compilePhase3AContent } from '../src/content/phase3a.js';
import type { ContentSource } from '../src/contracts/content-schema.js';
import type { PublicSnapshot, PublicEvent, FighterWorld } from '../src/contracts/fighter.js';
import type { CandidateTrace, OutcomeEstimate } from '../src/contracts/ai.js';
import type { DirectorCue } from '../src/contracts/pacing.js';
import { cueIntensity } from '../src/contracts/pacing.js';
import { PacingDirector } from '../src/director/pacing.js';
import { UtilityRunner } from '../src/runner/utility.js';
import { fighterConfig } from '../src/runner/fighter.js';
import { initialFighterState, fighterWorldHash } from '../src/sim/fighter-state.js';
import { publicSnapshot } from '../src/replay/frame.js';
import { replayInputs } from '../src/runner/input-replay.js';
import { hashCanonical } from '../src/math/hash.js';
import { ObservationBuffer } from '../src/runner/observation.js';
import { emptyMemory, emptyExecution } from '../src/ai/memory.js';
import { buildBelief } from '../src/ai/belief.js';
import { scoreOutcome } from '../src/ai/score.js';
import { distanceBand } from '../src/ai/abilities.js';
import { applyDirectorScores } from '../src/ai/director-score.js';
import { eligiblePool, choose } from '../src/ai/selection.js';
import type { PredictionContext } from '../src/ai/prediction.js';
const source = JSON.parse(readFileSync('content/fighter-phase3b.json', 'utf8')) as ContentSource, content = compilePhase3BContent(source), profile = content.source.pacingProfiles[0]!;
const initial = publicSnapshot(initialFighterState(fighterConfig(content), content, 'phase3b-v1'), [], content);
const frame = (tick: number, events: PublicEvent[] = [], ready = false): PublicSnapshot => ({ ...initial, tick, events, fighters: initial.fighters.map(f => ({ ...f, energyBand: ready ? 'ready' : 'low' })) });
const event = (seq: number, tick: number, detail: PublicEvent['detail'], sourceId = 1): PublicEvent => ({ seq, sourceTick: tick - 1, sourceId, targetId: sourceId === 1 ? 2 : 1, detail });
function advance(d: PacingDirector, end: number, fn = (t: number) => frame(t)) { let next = (d.lastConsumedSnapshotTick ?? -1) + 1; while (d.nextUpdateTick <= end) {
    const now = d.nextUpdateTick, cutoff = now - 10, frames = [];
    while (next <= cutoff)
        frames.push(fn(next++));
    d.update(frames, now);
} return d.currentCue; }
describe('public director protocol', () => {
    it('director rejects snapshots newer than the shared public delay', () => { const d = new PacingDirector(content, profile, 'pace', true, 31); d.update([], 0); expect(() => d.update([frame(0)], 30)).toThrow('immature'); });
    it('an opponent approach cannot make an unmoving mobility cast effective', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 60, t => { const f = frame(t, t === 1 ? [event(1, t, { kind: 'cast', castId: 1, abilityId: 'rubber-dash', slot: 'skill1' })] : []); return { ...f, fighters: f.fighters.map(actor => actor.id === 2 && t > 5 ? { ...actor, position: { x: actor.position.x - 200, y: actor.position.y } } : actor) }; }); expect(d.snapshot().pendingPublicCasts.every(p => !p.effective)).toBe(true); expect(d.snapshot().completedUses.every(p => !p.effective)).toBe(true); });
    it('validates pacing profile integer bounds and both ramps', () => { const raw = structuredClone(source); raw.pacingProfiles[0]!.rampTicks = 61; expect(() => compilePhase3BContent(raw)).toThrow('ramps'); raw.pacingProfiles[0]!.rampTicks = 1.5; expect(() => compilePhase3BContent(raw)).toThrow(); });
    it('opening protection and maturity enforce the first cold cue at tick 210', () => { const d = new PacingDirector(content, profile, 'observe'); expect(advance(d, 180)).toBeNull(); const cue = advance(d, 210)!; expect(cue.kind).toBe('engage'); expect(cue.basedOnTick).toBe(200); expect(cue.applyTick).toBe(211); expect(cue.expiresTick).toBe(331); });
    it('consumes intermediate damage instead of sampling just the final frame', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 210, t => frame(t, t === 190 ? [event(1, t, { kind: 'damage', castId: 1, amount: 5 })] : [])); expect(d.currentCue).toBeNull(); expect(d.snapshot().lastEffectiveInteractionTick).toBe(190); expect(d.lastConsumedSnapshotTick).toBe(200); });
    it('sub-HP damage accumulates to one before resetting quiet time', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 180, t => frame(t, t === 150 || t === 160 ? [event(t, t, { kind: 'damage', castId: 1, amount: .4 })] : [])); expect(d.snapshot().lastEffectiveInteractionTick).toBe(0); advance(d, 210, t => frame(t, t === 190 ? [event(t, t, { kind: 'damage', castId: 1, amount: .4 })] : [])); expect(d.snapshot().lastEffectiveInteractionTick).toBe(190); expect(d.currentCue).toBeNull(); });
    it('missing frames, private fields and duplicate public events fail closed', () => { const a = new PacingDirector(content, profile, 'observe'); a.update([], 0); expect(() => a.update([frame(1)], 30)).toThrow('missing'); const b = new PacingDirector(content, profile, 'observe'); b.update([], 0); expect(() => b.update(Array.from({ length: 21 }, (_, i) => ({ ...frame(i), futureInput: [] } as PublicSnapshot)), 30)).toThrow(); const c = new PacingDirector(content, profile, 'observe'); expect(() => advance(c, 30, t => frame(t, t === 1 || t === 2 ? [event(1, t, { kind: 'jump' })] : []))).toThrow('duplicate'); });
    it.each(['defend', 'reflect'] as const)('%s is an effective interaction', kind => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 210, t => frame(t, t === 190 ? [event(1, t, kind === 'defend' ? { kind, castId: 1, preventedDamage: 2 } : { kind, projectileId: 3, castId: 2, defenseCastId: 1, reflectionCount: 1, preventedDamage: 2 })] : [])); expect(d.currentCue).toBeNull(); expect(d.snapshot().lastEffectiveInteractionTick).toBe(190); });
    it('cue envelope ramps, holds and fades with half-open expiry', () => { const d = new PacingDirector(content, profile, 'observe'), c = advance(d, 210)!; expect([211, 226, 241, 271, 301, 316, 331].map(t => cueIntensity(c, t, 30))).toEqual([0, .5, 1, 1, 1, .5, 0]); });
    it('cue stays fixed during interactions and has a full neutral gap', () => { const d = new PacingDirector(content, profile, 'observe'), first = advance(d, 210)!; advance(d, 330, t => frame(t, t === 250 ? [event(1, t, { kind: 'damage', castId: 1, amount: 4 })] : [])); expect(d.currentCue?.id).toBe(first.id); advance(d, 360); expect(d.currentCue).toBeNull(); advance(d, 450); expect(d.currentCue).toBeNull(); expect(advance(d, 480)?.id).toBe(2); expect(d.records.filter(r => r.type === 'issued')).toHaveLength(2); expect(d.records.some(r => r.type === 'fade')).toBe(true); });
    it('emits at most six cues and retains at most 361 source frames', () => { const d = new PacingDirector(content, profile, 'pace'); advance(d, 3600); expect(d.snapshot().emittedCueCount).toBe(6); expect(d.snapshot().recentPublicSamples).toHaveLength(361); expect(d.records.filter(r => r.type === 'issued')).toHaveLength(6); });
    it('logging toggles cannot change director state or cues', () => { const a = new PacingDirector(content, profile, 'pace'), b = new PacingDirector(content, profile, 'pace', false); advance(a, 1200); advance(b, 1200); expect(a.snapshot()).toEqual(b.snapshot()); expect(b.records).toHaveLength(0); });
    it('ready hold survives the finite window and recent combat protects showcase', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 210, t => frame(t, t === 120 ? [event(1, t, { kind: 'damage', castId: 1, amount: 4 })] : [], true)); expect(d.currentCue?.kind).toBe('showcase'); const b = new PacingDirector(content, profile, 'observe'); advance(b, 210, t => frame(t, t === 180 ? [event(1, t, { kind: 'damage', castId: 1, amount: 4 })] : [], true)); expect(b.currentCue).toBeNull(); });
    it('cold engage takes priority over energy ready', () => { const d = new PacingDirector(content, profile, 'observe'); expect(advance(d, 210, t => frame(t, [], true))?.kind).toBe('engage'); });
    it('three settled basic misses trigger vary before showcase', () => { const d = new PacingDirector(content, profile, 'observe'); const casts = [70, 95, 120]; advance(d, 210, t => { const events: PublicEvent[] = []; if (t === 60)
        events.push(event(t, t, { kind: 'damage', castId: 9, amount: 4 })); if (casts.includes(t))
        events.push(event(t, t, { kind: 'cast', castId: t, abilityId: 'standard-jab', slot: 'basic' })); return frame(t, events, true); }); expect(d.currentCue?.kind).toBe('vary'); expect(d.currentCue?.evidence.misses.find(m => m.actorId === 1 && m.slot === 'basic')?.count).toBe(3); });
    it('an effective use resets earlier misses, so continuous attacks are not penalized', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 210, t => frame(t, [70, 95, 120].includes(t) ? [event(t, t, { kind: 'cast', castId: t, abilityId: 'standard-jab', slot: 'basic' })] : t === 130 ? [event(t, t, { kind: 'damage', castId: 120, amount: 4 })] : [])); expect(d.currentCue).toBeNull(); });
    it('effective use during a cue clears live repeated misses without restarting the envelope', () => { const d = new PacingDirector(content, profile, 'pace'); advance(d, 210, t => frame(t, t === 60 ? [event(t, t, { kind: 'damage', castId: 9, amount: 4 })] : [70, 95, 120].includes(t) ? [event(t, t, { kind: 'cast', castId: t, abilityId: 'standard-jab', slot: 'basic' })] : [])); const cue = d.currentCue!; advance(d, 240, t => frame(t, t === 211 ? [event(t, t, { kind: 'cast', castId: 211, abilityId: 'standard-jab', slot: 'basic' })] : t === 220 ? [event(t, t, { kind: 'damage', castId: 211, amount: 4 })] : [])); expect(d.currentCue?.id).toBe(cue.id); expect(d.currentCue?.expiresTick).toBe(cue.expiresTick); expect(d.currentCue?.liveEvidence?.evidence.misses.find(m => m.actorId === 1 && m.slot === 'basic')?.count).toBe(0); });
    it('miss confirmation waits for declared projectile lifetime and all visible emissions', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 90, t => frame(t, t === 1 ? [event(1, t, { kind: 'cast', castId: 1, abilityId: 'standard-bolt', slot: 'skill1' })] : [])); expect(d.snapshot().completedUses).toHaveLength(0); const due = d.snapshot().pendingPublicCasts[0]!.latestPossibleEffectEndTick; advance(d, due + 45); expect(d.snapshot().pendingPublicCasts).toHaveLength(0); expect(d.snapshot().completedUses[0]?.effective).toBe(false); });
    it('reflecting an enemy shot does not credit its original attack cast', () => { const d = new PacingDirector(content, profile, 'observe'); advance(d, 90, t => frame(t, t === 1 ? [event(1, t, { kind: 'cast', castId: 1, abilityId: 'standard-bolt', slot: 'skill1' })] : t === 50 ? [event(2, t, { kind: 'damage', castId: 1, amount: 4 }, 2)] : [])); expect(d.snapshot().pendingPublicCasts[0]?.effective).toBe(false); });
    it('third barrier contact credits dissipation to the defense rather than the original shot', () => {
        const d = new PacingDirector(content, profile, 'observe');
        advance(d, 90, t => frame(t, t === 1 ? [event(1, t, {kind:'cast',castId:1,abilityId:'mirror-screen',slot:'skill1'}), event(2,t,{kind:'cast',castId:2,abilityId:'standard-bolt',slot:'skill1'},2)] : t === 10 ? [event(3,t,{kind:'dissipate',projectileId:1,castId:2,defenseCastId:1,reflectionCount:3})] : []));
        expect(d.snapshot().lastEffectiveInteractionTick).toBe(10);
        expect(d.snapshot().completedUses.find(p=>p.castId===1)?.effective).toBe(true);
        expect(d.snapshot().pendingPublicCasts.find(p=>p.castId===2)?.effective).toBe(false);
    });
    it('a publicly visible buff is credited on its last active source tick', () => {
        const d = new PacingDirector(content, profile, 'observe');
        advance(d, 300, t => {
            const f = frame(t,t===1?[event(1,t,{kind:'cast',castId:1,abilityId:'rubber-overdrive',slot:'ultimate'})]:t===13?[event(2,t,{kind:'status',castId:1,statusId:'overdrive',expiresTick:252})]:t===252?[event(3,t,{kind:'growth',stacks:1})]:[]);
            return {...f,fighters:f.fighters.map(actor=>actor.id===1?{...actor,visibleEffects:t>=13&&t<252?[{castId:1,statusId:'overdrive',expiresTick:252}]:[]}:actor)};
        });
        expect(d.snapshot().completedUses.find(p=>p.castId===1)?.effective).toBe(true);
    });
    it('serialized state resumes the same cue suffix during plateau and fade', () => { for (const tick of [180, 240, 330]) {
        const a = new PacingDirector(content, profile, 'pace');
        advance(a, tick);
        const cp = JSON.parse(JSON.stringify(a.snapshot())), b = new PacingDirector(content, profile, 'pace');
        b.restore(cp);
        advance(a, 720);
        advance(b, 720);
        expect(a.snapshot()).toEqual(b.snapshot());
        expect(a.records.filter(r => r.tick > tick)).toEqual(b.records);
    } });
});
const estimate: OutcomeEstimate = { expectedDamageDealtPct: 0, meanDamageTakenPct: 0, worstDamageTakenPct: 0, killLikelihood: 0, deathLikelihood: 0, positionQualityBefore: 0, positionQualityAfter: 0, bandProgressPx: 120, residualExposurePct: 0, setupValue: 0, confidence: 1, earlyRiskPct: 0, hitTicks: [], segmentsUsed: 5, budgetExceeded: false, setupConfidence: 1, setupReason: 'test' };
function context(kind: DirectorCue['kind']): PredictionContext { const raw = structuredClone(source); raw.profiles.forEach(p => p.reactionDelayTicks = 0); const content = compilePhase3BContent(raw), w = structuredClone(initialFighterState(fighterConfig(content), content, 'phase3b-v1')) as FighterWorld; w.tick = 250; w.entities[0].energy = 100; const buffer = new ObservationBuffer(content); buffer.push(w, [], []); const o = { ...buffer.observe(w, 0), directorCue: { id: 1, kind, issuedTick: 210, basedOnTick: 200, applyTick: 211, expiresTick: 331, profileId: profile.id, profileVersion: profile.version, evidence: { quietTicks: 200, lastEffectiveInteractionTick: 0, ready: [{ entityId: 1, sinceTick: 0 }], misses: [{ actorId: 1, slot: 'basic' as const, count: 3 }] } } }; const p = content.source.profiles[0]!, memory = emptyMemory(), execution = emptyExecution(), settings = { noise: false, randomChoice: false, memory: true }; return { observation: o, content, profile: p, memory, execution, settings, belief: buildBelief(o, content, p, memory, 0, settings) }; }
function candidate(c: PredictionContext, Uraw = 1, slot: CandidateTrace['option']['slot'] = null, out: Partial<OutcomeEstimate> = {}): CandidateTrace { return { option: { key: slot ?? 'move', kind: slot ? 'cast' : 'move', moveX: 1, slot, aimX: 1, legal: true, reason: null, tag: 'test' }, outcome: { ...estimate, ...out }, score: { ...scoreOutcome(estimate, c.profile, 1, 0, 0), Uraw }, eligible: false, switchMargin: 0 }; }
describe('bounded director score and selection', () => {
    it('engage caps at 1.2 and uses the existing predictor band progress', () => { const c = context('engage'), v = candidate(c); applyDirectorScores(c, [v], v); expect(v.score!.Ubase).toBe(1); expect(v.score!.director?.applied).toBe(1.2); expect(v.score!.Uraw).toBe(2.2); });
    it('own stuck bonus and engage sum cannot exceed 2.5', () => { const c = context('engage'), v = candidate(c); v.score!.stuckBonus = 2; applyDirectorScores(c, [v], v); expect(v.score!.director?.raw).toBe(1.2); expect(v.score!.director?.applied).toBe(.5); });
    it('engage has no bonus inside the legal main-attack band', () => { const c = context('engage'), band = distanceBand(c.observation, c.content, c.profile, 250); c.belief.opponent!.position = { x: c.observation.self.entity.body.position.x + (band[0] + band[1]) / 2, y: 32 }; const v = candidate(c); applyDirectorScores(c, [v], v); expect(v.score!.director?.applied).toBe(0); });
    it.each([-30, 0])('no engage for non-positive progress %s', progress => { const c = context('engage'), v = candidate(c, 1, null, { bandProgressPx: progress }); applyDirectorScores(c, [v], v); expect(v.score!.director?.applied).toBe(0); });
    it('positive bonus cannot rescue a base candidate outside 1.2 or extra death risk', () => { const c = context('engage'), best = candidate(c, 2), bad = candidate(c, .7), risky = candidate(c, 1, null, { deathLikelihood: .051 }); applyDirectorScores(c, [best, bad, risky], best); expect(bad.score!.director?.baseAllowed).toBe(false); expect(bad.score!.director?.applied).toBe(0); expect(risky.score!.director?.riskAllowed).toBe(false); expect(risky.score!.director?.applied).toBe(0); });
    it('vary uses own actor/slot misses and combined R cost caps at 1', () => { const c = context('vary'), v = candidate(c, 1, 'basic'), other = candidate(c, 1, 'skill1'); v.score!.R = .8; applyDirectorScores(c, [v, other], v); expect(v.score!.director?.raw).toBe(-.6); expect(v.score!.director?.applied).toBeCloseTo(-.2); expect(other.score!.director?.applied).toBe(0); });
    it('vary can change selected action while preserving commitment selection machinery', () => { const c = context('vary'), basic = candidate(c, 1, 'basic'), alternative = candidate(c, .7, 'skill1'); expect(choose(eligiblePool([basic, alternative], null, false, false), 0, false)?.option.slot).toBe('basic'); applyDirectorScores(c, [basic, alternative], basic); expect(choose(eligiblePool([basic, alternative], null, false, false), 0, false)?.option.slot).toBe('skill1'); });
    it('ineffective ultimate does not receive showcase', () => { const c = context('showcase'), v = candidate(c, 1, 'ultimate'); applyDirectorScores(c, [v], v); expect(v.score!.director?.applied).toBe(0); });
    it.each([{ expectedDamageDealtPct: 1 }, { setupValue: .5 }, { meanDamageTakenPct: 0 }])('showcase requires a predicted useful ultimate %j', out => { const c = context('showcase'), v = candidate(c, .7, 'ultimate', out), current = candidate(c, 1, null, { meanDamageTakenPct: 3 }); applyDirectorScores(c, [v, current], current); expect(v.score!.director?.applied).toBe(.8); expect(choose(eligiblePool([v, current], null, false, false), 0, false)?.option.slot).toBe('ultimate'); });
    it('no cue leaves scores byte-for-byte unchanged', () => { const c = context('engage'); delete c.observation.directorCue; const v = candidate(c), before = JSON.stringify(v); applyDirectorScores(c, [v], v); expect(JSON.stringify(v)).toBe(before); });
});
describe('runner replay invariants', () => {
    it('freezes run configuration and settings against later caller mutation',()=>{const cfg=fighterConfig(content,17,'standard','rubber',180);cfg.pacing={mode:'observe',profileId:profile.id};const settings={noise:true,randomChoice:true,memory:true},a=new UtilityRunner(content,cfg,{settings,recordFrames:false}),before=a.runnerHash();cfg.pacing.mode='pace';settings.noise=false;expect(a.config.pacing.mode).toBe('observe');expect(a.options.settings.noise).toBe(true);expect(a.runnerHash()).toBe(before);expect(()=>{a.config.pacing.mode='pace';}).toThrow();});
    it('ring grows for maximum reaction delay and slower sampling; restored observe still matches off', () => { const raw = structuredClone(source); raw.profiles.forEach(p => p.reactionDelayTicks = 30); raw.pacingProfiles[0]!.sampleIntervalTicks = 60; const c = compilePhase3BContent(raw), cfg = fighterConfig(c, 17, 'standard', 'rubber', 180); cfg.pacing = { mode: 'observe', profileId: profile.id }; const a = new UtilityRunner(c, cfg, { recordFrames: false }); for (let t = 0; t < 120; t++)
        a.step(); expect(a.observations.capacity).toBe(93); expect(a.snapshot().observations.ring).toHaveLength(93); const b = new UtilityRunner(c, cfg, { recordFrames: false }); b.restore(a.snapshot(true)); expect(b.run().inputs).toEqual(a.run().inputs); const offCfg = structuredClone(cfg); offCfg.pacing = { mode: 'off', profileId: null }; expect(new UtilityRunner(c, offCfg, { recordFrames: false }).run().inputs).toEqual(a.replay().inputs); });
    it('off and observe inputs match and logs/trace toggles cannot affect pace', () => { const cfg = fighterConfig(content, 17, 'mirror', 'rubber', 600), off = new UtilityRunner(content, cfg, { recordFrames: false }), observeCfg = structuredClone(cfg); observeCfg.pacing = { mode: 'observe', profileId: profile.id }; const observe = new UtilityRunner(content, observeCfg, { trace: true, recordFrames: false }); expect(off.run().inputs).toEqual(observe.run().inputs); const paceCfg = structuredClone(observeCfg); paceCfg.pacing.mode = 'pace'; const a = new UtilityRunner(content, paceCfg, { trace: true, recordFrames: false }), b = new UtilityRunner(content, paceCfg, { directorLog: false, recordFrames: false }); expect(a.run().inputs).toEqual(b.run().inputs); expect(a.runnerHash()).toBe(b.runnerHash()); });
    it.each([209, 260, 320])('full checkpoint around a cold cue restores tick %s with same complete recording', tick => { const cfg = fighterConfig(content, 17, 'standard', 'rubber', 600); cfg.pacing = { mode: 'pace', profileId: profile.id }; const a = new UtilityRunner(content, cfg, { kinds: ['idle', 'idle'], recordFrames: false }); while (a.sim.snapshot().tick < tick)
        a.step(); const cp = JSON.parse(JSON.stringify(a.snapshot(true))), b = new UtilityRunner(content, cfg, { kinds: ['idle', 'idle'], recordFrames: false }); b.restore(cp); while (!a.sim.snapshot().result) {
        a.step();
        b.step();
        expect(b.inputs.at(-1)).toEqual(a.inputs.at(-1));
        expect(fighterWorldHash(b.sim.snapshot())).toBe(fighterWorldHash(a.sim.snapshot()));
    } expect(b.runnerHash()).toBe(a.runnerHash()); expect(b.replay()).toEqual(a.replay()); expect(replayInputs(a.replay(), false).replay.finalWorldHash).toBe(a.replay().finalWorldHash); });
    it('director future state is hashed and cannot be removed from an enabled checkpoint', () => { const cfg = fighterConfig(content, 17, 'standard', 'rubber', 600); cfg.pacing = { mode: 'pace', profileId: profile.id }; const a = new UtilityRunner(content, cfg); for (let t = 0; t < 240; t++)
        a.step(); const cp = structuredClone(a.snapshot()); cp.pacingDirector!.lastEffectiveInteractionTick++; expect(() => new UtilityRunner(content, cfg).restore(cp)).toThrow('runnerHash'); cp.pacingDirector = null; const { runnerHash, ...future } = cp; cp.runnerHash = hashCanonical(future); expect(() => new UtilityRunner(content, cfg).restore(cp)).toThrow('pacing'); });
    it('supported old input replays migrate a missing pacing field explicitly to off', () => { const legacy = compilePhase3AContent(JSON.parse(readFileSync('content/fighter-phase3a.json', 'utf8'))), a = new UtilityRunner(legacy, fighterConfig(legacy, 17, 'standard', 'rubber', 60)), r = structuredClone(a.run()); delete (r.config as Partial<typeof r.config>).pacing; expect(replayInputs(r, false).replay.config.pacing).toEqual({ mode: 'off', profileId: null }); });
});
