import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { ContentSource } from '../src/contracts/content-schema.js';
import type { FighterWorld, BattleEvent } from '../src/contracts/fighter.js';
import type { Option } from '../src/contracts/ai.js';
import { NEUTRAL_INTENT, type ActionIntent } from '../src/contracts/state.js';
import { compilePhase3AContent } from '../src/content/phase3a.js';
import { compileFighterContent } from '../src/content/fighter.js';
import { compileUtilityContent } from '../src/content/utility.js';
import { initialFighterState, fighterWorldHash } from '../src/sim/fighter-state.js';
import { FighterSimulation } from '../src/sim/fighter.js';
import { effective, applyBodyAttributes } from '../src/sim/abilities/effective.js';
import { fighterConfig } from '../src/runner/fighter.js';
import { UtilityRunner } from '../src/runner/utility.js';
import { ObservationBuffer } from '../src/runner/observation.js';
import { replayInputs } from '../src/runner/input-replay.js';
import { UtilityController } from '../src/ai/utility.js';
import { baselineSlots } from '../src/ai/baseline-rules.js';
import { BaselineController } from '../src/ai/scripted.js';
import { buildBelief } from '../src/ai/belief.js';
import { emptyMemory, emptyExecution, beginOwnResult, consumeMemory } from '../src/ai/memory.js';
import { predictOutcome, predictionGrid, buildThreats, type PredictionContext } from '../src/ai/prediction.js';
import { scoreOption } from '../src/ai/score.js';
import { reflectVelocity, speedImpactDamage, statusGeometry } from '../src/math/ability-effects.js';
import { deriveParticipantSeed, Xoshiro128ss } from '../src/math/random.js';
import { publicSnapshot } from '../src/replay/frame.js';
import { aggregateEvaluation, evaluationMetrics } from '../src/analysis/evaluation.js';
const source=JSON.parse(readFileSync('content/fighter-phase3a.json','utf8')) as ContentSource;
const diagnostic=structuredClone(source);
for(const p of diagnostic.profiles){p.reactionDelayTicks=0;p.positionNoisePx=0;p.velocityNoisePxPerSecond=0;}
const content=compilePhase3AContent(diagnostic),production=compilePhase3AContent(source),profile=content.source.profiles.find(p=>p.id==='balanced')!,settings={noise:false,randomChoice:false,memory:true};
const cast=(slot:'basic'|'skill1'|'skill2'|'ultimate',requestId=1,aimX:1|-1=1):ActionIntent=>({...NEUTRAL_INTENT,cast:{slot,aimX},requestId});
const option=(slot:Option['slot']=null,moveX:-1|0|1=0):Option=>({key:`${slot??'move'}:${moveX}`,kind:slot?'cast':'move',moveX,slot,aimX:1,legal:true,reason:null,tag:'test'});
function scene(a='mirror',b='standard',edit:(w:FighterWorld)=>void=()=>{},bundle=content){
  const config=fighterConfig(bundle,17,a,b),w=structuredClone(initialFighterState(config,bundle,'phase3a-v1')) as FighterWorld;
  w.entities[0].body.position.x=400;w.entities[1].body.position.x=800;edit(w);
  const buffer=new ObservationBuffer(bundle);buffer.push(w,[],[]);const o=buffer.observe(w,0),memory=emptyMemory(),execution=emptyExecution();
  const c:PredictionContext={observation:o,content:bundle,profile,settings,memory,execution,belief:buildBelief(o,bundle,profile,memory,17,settings)};
  return {w,o,c,config,sim:new FighterSimulation(bundle,config,w,'phase3a-v1')};
}
function shield(w:FighterWorld,index:0|1,statusId='dome',castId:number|null=null){w.entities[index].statuses.push({instanceId:w.nextStatusId++,definitionId:statusId,sourceId:index+1,sourceCastId:castId,appliedTick:0,expiresTick:180,stacks:1});}
function projectile(w:FighterWorld,x:number,y:number,vx=720,vy=0,ownerId=2,abilityId='standard-bolt'){
  const definition=content.source.abilities.find(a=>a.id===abilityId)!,fx=definition.timeline.flatMap(t=>t.effects).find(f=>f.kind==='projectile')!;
  if(fx.kind!=='projectile')throw Error('test effect');
  const castId=w.nextCastId++;w.casts.push({castId,rootEventSeq:w.nextEventSeq++,ownerId,requestId:1,abilityId,aimX:vx>0?1:-1,startedTick:0,endsTick:40,firstEmissionTick:0,interruptedTick:null,finishedTick:null,scheduledPolicy:'cancel-on-interrupt'});
  w.projectiles.push({id:w.nextEntityId++,ownerId,sourceCastId:castId,abilityId,position:{x,y},velocity:{x:vx,y:vy},radius:12,expiresTick:180,reflectionCount:0,ignoreOwnerUntilOutside:false,hit:structuredClone(fx.hit)});
}
const advance=(sim:FighterSimulation,ticks:number):BattleEvent[]=>{const events:BattleEvent[]=[];for(let i=0;i<ticks&&!sim.snapshot().result;i++)events.push(...sim.step([NEUTRAL_INTENT,NEUTRAL_INTENT]).events);return events;};

describe('Phase 3A content and iron mechanisms',()=>{
  it('four characters have sixteen complete slots and all four profiles',()=>{expect(production.source.characters).toHaveLength(4);expect(production.source.abilities).toHaveLength(16);expect(production.source.profiles.map(p=>p.id)).toEqual(['balanced','counter','evasive','pressure']);expect(production.pluginVersions).toEqual({'reflect-projectile':1,'rubber-wall-growth':1,'speed-impact':1});expect(()=>compileFighterContent(source)).toThrow();expect(()=>compileUtilityContent(source)).toThrow();});
  it('speed-impact params reject extra fields, nonfinite values and uncapped bonuses',()=>{for(const params of [{thresholdSpeed:400,speedScale:800,maxBonus:1},{thresholdSpeed:400,speedScale:0,maxBonus:.75},{thresholdSpeed:400,speedScale:800,maxBonus:.75,hidden:true}]){const bad=structuredClone(source);bad.passives.find(p=>p.id==='speed-impact')!.effects=[{kind:'plugin',pluginId:'speed-impact',params}];expect(()=>compilePhase3AContent(bad)).toThrow();}});
  it('relative speed only multiplies dash-hit and caps at 1.75',()=>{expect(speedImpactDamage(content,'iron','iron-charge',9,400)).toBe(9);expect(speedImpactDamage(content,'iron','iron-charge',9,800)).toBe(13.5);expect(speedImpactDamage(content,'iron','iron-charge',9,3600)).toBe(15.75);expect(speedImpactDamage(content,'iron','iron-smash',11,1800)).toBe(11);expect(speedImpactDamage(content,'rubber','rubber-dash',10,1800)).toBe(10);});
  it('charge uses first swept relative contact, hits once, without damaging bare body collisions',()=>{const {sim}=scene('iron','standard',w=>{w.entities[0].body.position.x=400;w.entities[1].body.position.x=535;});sim.step([cast('skill1'),NEUTRAL_INTENT]);const events=advance(sim,45),damage=events.filter(e=>e.type==='DamageResolved');expect(damage).toHaveLength(1);expect(damage[0]!.payload.amount).toBeGreaterThan(9);expect(damage[0]!.payload.amount).toBeLessThanOrEqual(15.75);const body=scene('iron','standard',w=>{w.entities[1].body.position.x=470;w.entities[0].body.velocity.x=1800;});expect(advance(body.sim,10).some(e=>e.type==='DamageResolved')).toBe(false);});
  it('brace applies exact mitigation and mass remains solely the character mass',()=>{const {sim}=scene('iron','standard',w=>shield(w,0,'brace'));const e=sim.snapshot().entities[0],m=effective(e,content,0);expect(m.damageTaken).toBe(.7);expect(m.knockbackTaken).toBe(.4);expect(m.moveSpeed).toBe(270*.6);expect(e.body.mass).toBe(1.6);});
  it('giant projects expansion inside floor/wall, changes public geometry and restores from base',()=>{const {sim}=scene('iron','standard',w=>{w.entities[0].energy=100;w.entities[0].body.position.x=36;});sim.step([cast('ultimate'),NEUTRAL_INTENT]);advance(sim,16);const giant=sim.snapshot().entities[0];expect(giant.body.radius).toBeCloseTo(48.6);expect(giant.body.mass).toBeCloseTo(2.24);expect(giant.body.position.x).toBeGreaterThanOrEqual(giant.body.radius);expect(giant.body.position.y).toBeGreaterThanOrEqual(giant.body.radius);expect(publicSnapshot(sim.snapshot(),[],content).fighters[0]!.radius).toBe(giant.body.radius);expect(effective(giant,content,17).meleeScale).toBe(1.25);advance(sim,240);expect(sim.snapshot().entities[0].body.radius).toBe(36);expect(sim.snapshot().entities[0].body.mass).toBe(1.6);expect(effective(sim.snapshot().entities[0],content,257).moveSpeed).toBe(270);});
  it('geometry multipliers obey refresh/max scale and do not compound body size',()=>{const {w:original}=scene('iron');const w=structuredClone(original);shield(w,0,'giant');shield(w,0,'giant');const geometry=statusGeometry(content,'iron',w.entities[0].statuses,0);expect(geometry.radius).toBeCloseTo(48.6);expect(geometry.mass).toBeCloseTo(1.6*1.4*1.4);applyBodyAttributes(w.entities[0],content,180,content.source.arenas[0]!);expect(w.entities[0].body.radius).toBe(36);expect(w.entities[0].body.mass).toBe(1.6);});
  it('iron predictor reads the same speed damage and giant hitbox scale',()=>{const {c}=scene('iron','standard',w=>{w.entities[1].body.position.x=545;});c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];const charge=predictOutcome(c,option('skill1'));expect(charge.expectedDamageDealtPct).toBeGreaterThan(9);expect(charge.expectedDamageDealtPct).toBeLessThanOrEqual(15.75);const giant=scene('iron','standard',w=>{shield(w,0,'giant');w.entities[1].body.position.x=520;});giant.c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];expect(predictOutcome(giant.c,option('basic')).expectedDamageDealtPct).toBeGreaterThan(0);});
});

describe('swept reflection, ownership and causal boundaries',()=>{
  it('head-on shield contact precedes body damage; returned damage and energy belong to reflector',()=>{const {sim}=scene('standard','mirror',w=>{w.entities[0].body.position.x=200;w.entities[1].body.position.x=600;shield(w,1);projectile(w,500,30,720,0,1);});const events=advance(sim,50),reflections=events.filter(e=>e.type==='ProjectileReflected'),damage=events.filter(e=>e.type==='DamageResolved');expect(reflections).toHaveLength(1);expect(reflections[0]!.sourceId).toBe(2);expect(reflections[0]!.payload.previousOwnerId).toBe(1);expect(reflections[0]!.payload.velocity.x).toBe(-720);expect(damage).toHaveLength(1);expect(damage[0]!.sourceId).toBe(2);expect(damage[0]!.targetId).toBe(1);expect(damage[0]!.rootEventId).toBe(reflections[0]!.rootEventId);expect(sim.snapshot().entities[1].hp).toBe(95);expect(sim.snapshot().entities[1].energy).toBeCloseTo(50/60+11*.35);expect(sim.snapshot().entities[0].energy).toBeCloseTo(50/60+11*.55);});
  it('oblique reflection preserves speed and uses the geometric normal',()=>{const {sim}=scene('standard','mirror',w=>{w.entities[0].body.position.x=200;w.entities[1].body.position.x=600;shield(w,1);projectile(w,500,60,720,0,1);});const reflected=advance(sim,10).find(e=>e.type==='ProjectileReflected');expect(reflected?.type).toBe('ProjectileReflected');if(reflected?.type!=='ProjectileReflected')throw Error('no reflection');const expected=reflectVelocity({x:720,y:0},{x:reflected.position!.x-600,y:reflected.position!.y-30});expect(reflected.payload.velocity.x).toBeCloseTo(expected.x);expect(reflected.payload.velocity.y).toBeCloseTo(expected.y);expect(Math.hypot(reflected.payload.velocity.x,reflected.payload.velocity.y)).toBeCloseTo(720);});
  it('double mirrors reflect twice and dissipate on the third shield contact',()=>{const {sim}=scene('mirror','mirror',w=>{w.entities[0].body.position.x=300;w.entities[1].body.position.x=600;shield(w,0);shield(w,1);projectile(w,500,30,820,0,1,'mirror-shard');});const events=advance(sim,70),refs=events.filter(e=>e.type==='ProjectileReflected');expect(refs.map(e=>e.payload.reflectionCount)).toEqual([1,2]);expect(events.filter(e=>e.type==='ProjectileDissipated')).toHaveLength(1);expect(events.some(e=>e.type==='DamageResolved')).toBe(false);expect(events.every(e=>e.depth<=4)).toBe(true);expect(sim.snapshot().projectiles).toHaveLength(0);});
  it('starting inside a shield reflects at most once per substep and ignores new owner until outside',()=>{const {sim}=scene('standard','mirror',w=>{w.entities[1].body.position.x=600;shield(w,1);projectile(w,600,30,720,0,1);});const first=sim.step([NEUTRAL_INTENT,NEUTRAL_INTENT]);expect(first.events.filter(e=>e.type==='ProjectileReflected')).toHaveLength(1);expect(first.events.some(e=>e.type==='DamageResolved')).toBe(false);expect(first.state.projectiles[0]!.ignoreOwnerUntilOutside).toBe(true);expect(first.state.projectiles[0]!.ownerId).toBe(2);advance(sim,8);expect(sim.snapshot().projectiles[0]?.ignoreOwnerUntilOutside).toBe(false);expect(sim.snapshot().entities[1].hp).toBe(95);});
  it('nonreflectable projectile and melee bypass the screen without damage reduction',()=>{const custom=structuredClone(diagnostic);const fx=custom.abilities.find(a=>a.id==='standard-bolt')!.timeline[0]!.effects[0]!;if(fx.kind!=='projectile')throw Error('effect');fx.reflectable=false;const bundle=compilePhase3AContent(custom),p=scene('standard','mirror',w=>{w.entities[1].body.position.x=600;shield(w,1);projectile(w,550,30,720,0,1);},bundle);const events=advance(p.sim,8);expect(events.some(e=>e.type==='ProjectileReflected')).toBe(false);expect(p.sim.snapshot().entities[1].hp).toBe(84);const melee=scene('standard','mirror',w=>{w.entities[0].body.position.x=400;w.entities[1].body.position.x=475;shield(w,1);});melee.sim.step([cast('basic'),NEUTRAL_INTENT]);advance(melee.sim,10);expect(melee.sim.snapshot().entities[1].hp).toBe(87);});
  it('half-open status expiry no longer intercepts a projectile',()=>{const {sim}=scene('standard','mirror',w=>{w.entities[1].body.position.x=600;shield(w,1,'screen');w.entities[1].statuses[0]!.expiresTick=1;projectile(w,520,30,720,0,1);});sim.step([NEUTRAL_INTENT,NEUTRAL_INTENT]);const events=advance(sim,5);expect(events.some(e=>e.type==='ProjectileReflected')).toBe(false);expect(sim.snapshot().entities[1].hp).toBe(84);});
  it('reflection-ignore radius and causal parent survive JSON snapshot restoration',()=>{const {sim,config}=scene('standard','mirror',w=>{w.entities[1].body.position.x=600;shield(w,1);projectile(w,600,30,720,0,1);});sim.step([NEUTRAL_INTENT,NEUTRAL_INTENT]);const restored=new FighterSimulation(content,config,JSON.parse(JSON.stringify(sim.snapshot())),'phase3a-v1');for(let i=0;i<20;i++){expect(restored.step([NEUTRAL_INTENT,NEUTRAL_INTENT])).toEqual(sim.step([NEUTRAL_INTENT,NEUTRAL_INTENT]));expect(fighterWorldHash(restored.snapshot())).toBe(fighterWorldHash(sim.snapshot()));}});
});

describe('Phase 3A public prediction, defense timing and controller evidence',()=>{
  it('public giant already active during its cast is not multiplied twice in a possible melee threat',()=>{const {c}=scene('mirror','iron',w=>{w.tick=37;w.entities[1].body.position.x=528;shield(w,1,'giant');w.entities[1].statuses[0]!.expiresTick=256;applyBodyAttributes(w.entities[1],content,37,content.source.arenas[0]!);w.entities[1].action={kind:'cast',castId:99,requestId:1,abilityId:'iron-giant',startedTick:0,startupTicks:16,activeTicks:1,recoveryTicks:22};});c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];expect(predictOutcome(c,option()).meanDamageTakenPct).toBe(0);});
  it('a visible brace startup changes damage at the predicted contact time, matching actual simulation',()=>{const {sim}=scene('mirror','iron',w=>{w.entities[1].body.position.x=500;});const out=sim.step([NEUTRAL_INTENT,cast('skill2',1,-1)]),buffer=new ObservationBuffer(content);buffer.push(out.state,out.events,out.receipts);const o=buffer.observe(out.state,0),memory=emptyMemory(),c:PredictionContext={observation:o,content,profile,settings,memory,execution:emptyExecution(),belief:buildBelief(o,content,profile,memory,17,settings)};c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];const prediction=predictOutcome(c,option('basic'));sim.step([cast('basic'),NEUTRAL_INTENT]);const actual=advance(sim,10).filter(e=>e.type==='DamageResolved').filter(e=>e.sourceId===1);expect(actual).toHaveLength(1);expect(prediction.expectedDamageDealtPct).toBeCloseTo(actual[0]!.payload.amount/110*100);expect(actual[0]!.payload.amount).toBeCloseTo(4.9);});
  it('AI-06 late screen receives no imaginary mitigation; an earlier projectile is actually reflected',()=>{
    const late=scene('mirror','standard',w=>projectile(w,470,30,-720)),early=scene('mirror','standard',w=>projectile(w,540,30,-720));
    for(const s of [late,early])s.c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];
    expect(predictOutcome(late.c,option('skill2')).meanDamageTakenPct).toBeCloseTo(predictOutcome(late.c,option()).meanDamageTakenPct);
    expect(predictOutcome(early.c,option('skill2')).meanDamageTakenPct).toBeLessThan(predictOutcome(early.c,option()).meanDamageTakenPct);
    const ctrl=new UtilityController(17,content,profile,settings),o={...early.o,self:{...early.o.self,legalSlots:['skill2'] as const,canMove:true,canJump:false},capabilities:{jump:false,horizontalMove:false}};const input=ctrl.update(o);expect(input.cast?.slot).toBe('skill2');early.sim.step([input,NEUTRAL_INTENT]);const events=advance(early.sim,29);expect(events.some(e=>e.type==='ProjectileReflected')).toBe(true);expect(early.sim.snapshot().entities[0].hp).toBe(95);
    late.sim.step([cast('skill2'),NEUTRAL_INTENT]);expect(advance(late.sim,15).some(e=>e.type==='DamageResolved'&&e.targetId===1)).toBe(true);
  });
  it('reflect startup and expiration are important prediction nodes',()=>{const {c}=scene();expect(predictionGrid(c,option('skill2'),buildThreats(c)).ticks).toEqual(expect.arrayContaining([6,24]));expect(predictionGrid(c,option('skill2'),buildThreats(c)).ticks.length-1).toBeLessThanOrEqual(12);});
  it('AI-07 and AI-14 mirror does not empty-cast screen/dome against melee-only opposition',()=>{const {o,c}=scene('mirror','iron',w=>{w.entities[1].body.position.x=560;w.entities[0].energy=100;});c.memory.ultimateReadySinceTick=0;expect(predictOutcome(c,option('skill2')).setupValue).toBe(0);expect(predictOutcome(c,option('ultimate')).setupValue).toBe(0);for(const profile of content.source.profiles){const ctrl=new UtilityController(17,content,profile,settings);for(let tick=0;tick<120;tick+=6){const input=ctrl.update({...o,nowTick:tick});expect(['skill2','ultimate']).not.toContain(input.cast?.slot);}}});
  it('mirror dome needs a real incoming window, and no aim-homing is predicted',()=>{const {c}=scene('mirror','standard',w=>{w.entities[0].energy=100;projectile(w,650,30,-720);});c.belief.hypotheses=[{kind:'keep',moveX:0,weight:1}];expect(predictOutcome(c,option('ultimate')).meanDamageTakenPct).toBeLessThan(predictOutcome(c,option()).meanDamageTakenPct);const miss=scene('mirror','standard',w=>{projectile(w,650,220,-720);});expect(predictOutcome(miss.c,option('skill2')).expectedDamageDealtPct).toBe(0);});
  it('giant has bounded setup only when a following attack is reachable',()=>{const near=scene('iron','standard',w=>{w.entities[1].body.position.x=540;w.entities[0].energy=100;}),far=scene('iron','standard',w=>{w.entities[1].body.position.x=900;w.entities[1].body.position.y=600;});expect(predictOutcome(near.c,option('ultimate')).setupValue).toBeGreaterThan(0);expect(predictOutcome(near.c,option('ultimate')).setupValue).toBeLessThanOrEqual(2);expect(predictOutcome(far.c,option('ultimate')).setupValue).toBe(0);});
  it('visible reflection marks its defense cast effective only after delivery, including after recovery',()=>{const {o,c}=scene('mirror');const memory=emptyMemory(),execution=emptyExecution();beginOwnResult(memory,o,content,profile,'skill2',1,1);memory.pendingOwnResults[0]!.accepted=true;memory.pendingOwnResults[0]!.castId=7;consumeMemory(memory,execution,{...o,nowTick:30,sensedTick:23,visibleEvents:[{seq:10,sourceTick:22,sourceId:1,targetId:2,detail:{kind:'reflect',projectileId:3,castId:4,defenseCastId:7,reflectionCount:1,preventedDamage:11}}]},content,profile,settings,[220,420]);expect(memory.pendingOwnResults[0]?.effective??memory.recentOwnResults[0]?.result).toBe('defended');expect(c.settings.memory).toBe(true);});
  it('AI-04 mirrored hidden enemy projectiles/statuses cannot change immature input or RNG',()=>{const w=structuredClone(initialFighterState(fighterConfig(production,17,'mirror','iron'),production,'phase3a-v1')) as FighterWorld,buffers=[new ObservationBuffer(production),new ObservationBuffer(production)],controllers=[new UtilityController(17,production,production.source.profiles.find(p=>p.id==='counter')!,settings),new UtilityController(17,production,production.source.profiles.find(p=>p.id==='counter')!,settings)];for(const b of buffers)b.push(w,[],[]);for(let tick=1;tick<8;tick++){const a=structuredClone(w);a.tick=tick;const b=structuredClone(a);b.entities[1].body.position.x=100;shield(b,1,'giant');projectile(b,480,30,-720);buffers[0]!.push(a,[],[]);buffers[1]!.push(b,[],[]);expect(controllers[0]!.update(buffers[0]!.observe(a,0))).toEqual(controllers[1]!.update(buffers[1]!.observe(b,0)));expect(controllers[0]!.snapshot().rngState).toEqual(controllers[1]!.snapshot().rngState);}});
});

describe('fair four-slot baselines, ablations and mode isolation',()=>{
  it('baseline applies the same profile error channels as Utility, respects no-noise and consumes one RNG draw',()=>{
    const profile=production.source.profiles.find(p=>p.id==='pressure')!,rng=new Xoshiro128ss(17),bits=rng.nextUint32();let changed=0;
    for(let x=510;x<=550;x++){
      const {o}=scene('iron','standard',w=>{w.entities[1].body.position.x=x;}),before=structuredClone(o);
      const belief=buildBelief(o,production,profile,emptyMemory(),bits,{noise:true,randomChoice:false,memory:false});
      const perturbed={...o,opponent:{...o.opponent!,position:belief.opponent!.position,velocity:belief.opponent!.velocity}};
      const noisy=new BaselineController('rush',17,production,{noise:true,profileId:'pressure'}),plain=new BaselineController('rush',17,production,{noise:false,profileId:'pressure'});
      const actual=noisy.update(o),expected=plain.update(perturbed),unperturbed=new BaselineController('rush',17,production,{noise:false,profileId:'pressure'}).update(o);
      expect(actual).toEqual(expected);expect(noisy.snapshot().rngState).toEqual(rng.snapshot());expect(o).toEqual(before);
      if(JSON.stringify(actual)!==JSON.stringify(unperturbed))changed++;
    }
    expect(changed).toBeGreaterThan(0);
  });
  it('Rush and Ranged can request every one of the sixteen slots in suitable public scenarios',()=>{
    for(const character of ['standard','rubber','iron','mirror'])for(const slot of ['basic','skill1','skill2','ultimate'] as const){
      const {o}=scene(character,'standard',w=>{
        const self=w.entities[0],enemy=w.entities[1];self.energy=100;
        enemy.body.position.x=slot==='basic'||character==='standard'&&slot==='skill2'?480:character==='rubber'||character==='iron'?600:800;
        if(slot==='skill2'&&character!=='standard'||slot==='ultimate'&&character==='mirror')projectile(w,slot==='ultimate'?650:570,self.body.position.y,-720);
        if(slot==='ultimate'&&character==='rubber'){self.body.position.x=280;self.body.velocity.x=-900;enemy.body.position.x=700;}
      });
      const observation={...o,self:{...o.self,legalSlots:[slot]}};
      for(const kind of ['rush','ranged'] as const)expect(new BaselineController(kind,17,content).update(observation).cast?.slot,`${kind}/${character}/${slot}`).toBe(slot);
    }
  });
  it('AI-14 ready-aged giant is actually selected in a public safe follow-up window',()=>{
    const {o}=scene('iron','standard',w=>{w.entities[0].energy=100;w.entities[1].body.position.x=540;w.entities[1].body.facing=1;w.entities[1].action={kind:'cast',castId:99,requestId:1,abilityId:'standard-volley',startedTick:0,startupTicks:18,activeTicks:1,recoveryTicks:24};});
    const observation={...o,nowTick:600,sensedTick:600,opponent:{...o.opponent!,tell:{abilityId:'standard-volley',phase:'startup' as const,visibleSinceTick:600},facing:1 as const},self:{...o.self,legalSlots:['ultimate'] as const,canJump:false},capabilities:{jump:false,horizontalMove:false}};
    const ctrl=new UtilityController(17,content,profile,settings),cp=structuredClone(ctrl.snapshot());cp.memory.ultimateReadySinceTick=0;ctrl.restore(cp);expect(ctrl.update(observation).cast?.slot).toBe('ultimate');
  });
  it('metrics use actual reflected defense ownership and null for absent denominators',()=>{const runner=new UtilityRunner(content,fighterConfig(content,17,'mirror','mirror',120),{kinds:['idle','idle']});const replay=runner.run(),metrics=evaluationMetrics(replay,runner.frames,1);expect(metrics.basicMissRate).toBeNull();expect(metrics.skillEffectiveRate).toBeNull();expect(metrics.invalidRequestRate).toBeNull();expect(metrics.firstInteractionSeconds).toBeNull();const rows=[{a:'mirror',baseline:'rush',split:'train',winner:null,reason:'timeout',metrics},{a:'mirror',baseline:'rush',split:'train',winner:'utility',reason:'ko',metrics}];expect(aggregateEvaluation(rows).winRate).toBe(.5);expect(aggregateEvaluation(rows).draws).toBe(1);expect(aggregateEvaluation(rows).noInteractionMatches).toBe(2);});
  it('both baselines refuse untimely/empty mirror defenses but can use screen/dome',()=>{const empty=scene('mirror','iron',w=>{w.entities[0].energy=100;w.entities[1].body.position.x=600;}),early=scene('mirror','standard',w=>{w.entities[0].energy=100;projectile(w,650,30,-720);}),late=scene('mirror','standard',w=>{w.entities[0].energy=100;projectile(w,470,30,-720);});expect(baselineSlots(empty.o,content,1,0)).not.toContain('skill2');expect(baselineSlots(empty.o,content,1,0)).not.toContain('ultimate');expect(baselineSlots(early.o,content,1,0)).toEqual(expect.arrayContaining(['skill2','ultimate']));expect(baselineSlots(late.o,content,1,0)).not.toContain('skill2');for(const kind of ['rush','ranged'] as const)expect(new BaselineController(kind,17,content).update(early.o).cast?.slot).toBe('ultimate');});
  it('both iron skills and giant have public actionable opportunities',()=>{const charge=scene('iron','standard',w=>{w.entities[1].body.position.x=600;w.entities[0].energy=100;}),brace=scene('iron','standard',w=>projectile(w,570,36,-720));expect(baselineSlots(charge.o,content,1,1)).toEqual(expect.arrayContaining(['skill1','ultimate']));expect(baselineSlots(brace.o,content,1,0)).toContain('skill2');const far=scene('iron','standard',w=>{w.entities[0].energy=100;w.entities[1].body.position.y=600;});expect(baselineSlots(far.o,content,1,0)).not.toContain('ultimate');});
  it('participant seed follows its identity after swapping sides',()=>{expect(deriveParticipantSeed(17,'utility')).not.toBe(deriveParticipantSeed(17,'baseline'));const config=fighterConfig(content,17,'mirror','mirror');config.participants[0].participantId='utility';config.participants[1].participantId='baseline';const a=new UtilityRunner(content,config,{kinds:['utility','rush']});config.participants.reverse();const b=new UtilityRunner(content,config,{kinds:['rush','utility']});expect(a.controllers[0].snapshot().rngState).toEqual(b.controllers[1].snapshot().rngState);});
  it('prediction ablation is static and records zero trajectory segments',()=>{const {c}=scene('mirror');c.settings={...settings,prediction:false};expect(predictOutcome(c,option('skill1')).segmentsUsed).toBe(0);expect(predictOutcome(c,option('skill1')).setupReason).toContain('prediction-disabled');});
  it('hysteresis ablation is serialized and does not disable legal actions or one-shot requests',()=>{const runner=new UtilityRunner(content,fighterConfig(content,17,'iron','mirror',180),{settings:{...settings,hysteresis:false}});const replay=runner.run();expect(runner.snapshot().settings.hysteresis).toBe(false);expect(replay.result.reason).not.toBe('invalid');expect(replay.events.some(e=>e.type==='ActionRejected')).toBe(false);for(const entity of [0,1]){const requests=replay.inputs.map(e=>e.intents[entity]!.requestId).filter(v=>v!==null);expect(new Set(requests).size).toBe(requests.length);}});
  it('FreeBounceFixture runs 600 ticks with zero gravity, fixed nonparallel velocities and disabled jump',()=>{const src=structuredClone(diagnostic);const arena=structuredClone(src.arenas[0]!);arena.id='free-bounce-test';arena.gravity={x:0,y:0};arena.spawnPositions=[{x:240,y:260},{x:720,y:600}];src.arenas.push(arena);const bundle=compilePhase3AContent(src),config=fighterConfig(bundle,17,'standard','standard',600);config.rulesetId='free-bounce-fixture';config.arenaId=arena.id;const runner=new UtilityRunner(bundle,config,{settings});expect(runner.sim.snapshot().entities.map(e=>e.body.velocity)).toEqual([{x:420,y:310},{x:-370,y:-260}]);expect(runner.observations.observe(runner.sim.snapshot(),0).capabilities.jump).toBe(false);const replay=runner.run();expect(replay.inputs).toHaveLength(600);expect(replay.events.some(e=>e.type==='Jumped')).toBe(false);expect(replay.events.some(e=>e.type==='ProjectileSpawned')).toBe(true);expect(replay.result.reason).toBe('timeout');expect(replayInputs(replay).replay.finalWorldHash).toBe(replay.finalWorldHash);const bad={...config,arenaId:bundle.source.arenas.find(a=>a.id!=='free-bounce-test')!.id};expect(()=>new UtilityRunner(bundle,bad)).toThrow(/zero gravity/);});
  it('FreeBounce direct jump requests are rejected and old builds cannot execute the fixture',()=>{const src=structuredClone(diagnostic);src.arenas[0]!.gravity={x:0,y:0};src.arenas[0]!.spawnPositions=[{x:240,y:260},{x:720,y:600}];const bundle=compilePhase3AContent(src),config=fighterConfig(bundle,17,'standard','standard',600);config.rulesetId='free-bounce-fixture';const sim=new FighterSimulation(bundle,config,undefined,'phase3a-v1');expect(sim.step([{...NEUTRAL_INTENT,jumpPressed:true,requestId:1},NEUTRAL_INTENT]).receipts[0]?.result).toBe('rejected');expect(()=>new FighterSimulation(bundle,config,undefined,'phase2-v1')).toThrow(/Fixture/);});
  it('complete checkpoints at 120/240 and end-minus-one retain all four-character future state',()=>{const cfg=fighterConfig(content,17,'iron','mirror',300),a=new UtilityRunner(content,cfg,{settings,trace:true,recordFrames:false}),checkpoints=[];while(!a.sim.snapshot().result){if([120,240,299].includes(a.sim.snapshot().tick))checkpoints.push(a.snapshot(true));a.step();}for(const cp of checkpoints){const b=new UtilityRunner(content,cfg,{settings,trace:false,recordFrames:false});b.restore(JSON.parse(JSON.stringify(cp)));while(!b.sim.snapshot().result)b.step();expect(b.replay()).toEqual(a.replay());expect(b.runnerHash()).toBe(a.runnerHash());}expect(a.replay().engineBuild).toBe('phase3a-v1');expect(()=>new UtilityRunner(content,cfg).restore({...a.snapshot(),engineBuild:'phase2-v1'})).toThrow();});
  it('full runner checkpoints preserve an actual giant and an in-flight reflection causal chain',()=>{
    for(const mechanism of ['giant','reflect']){
      // The giant checkpoint is a fixed diagnostic scenario with a noiseless baseline,
      // independent of policy changes in the fair competitive evaluation.
      const raw=structuredClone(source);raw.profiles.push({...raw.profiles.find(p=>p.id==='pressure')!,id:'checkpoint-baseline',positionNoisePx:0,velocityNoisePxPerSecond:0});
      const bundle=mechanism==='giant'?compilePhase3AContent(raw):production;
      const cfg=fighterConfig(bundle,mechanism==='giant'?2816344454:4040648322,mechanism==='giant'?'iron':'mirror',mechanism==='giant'?'iron':'mirror');
      const kinds=mechanism==='giant'?['rush','utility'] as const:['utility','utility'] as const;
      if(mechanism==='giant'){cfg.participants[0].participantId='baseline';cfg.participants[1].participantId='utility';cfg.participants[0].profileId='checkpoint-baseline';}
      const a=new UtilityRunner(bundle,cfg,{kinds,recordFrames:false});
      const present=()=>mechanism==='giant'?a.sim.snapshot().entities.some(e=>e.statuses.some(s=>s.definitionId==='giant')):a.sim.snapshot().projectiles.some(p=>p.reflectionCause&&p.ignoreOwnerUntilOutside);
      while(!a.sim.snapshot().result&&!present())a.step();expect(present(),mechanism).toBe(true);
      const b=new UtilityRunner(bundle,cfg,{kinds,recordFrames:false});b.restore(JSON.parse(JSON.stringify(a.snapshot(true))));expect(b.runnerHash()).toBe(a.runnerHash());
      while(!a.sim.snapshot().result){a.step();b.step();expect(b.inputs.at(-1)).toEqual(a.inputs.at(-1));expect(fighterWorldHash(b.sim.snapshot())).toBe(fighterWorldHash(a.sim.snapshot()));}
      expect(b.replay()).toEqual(a.replay());expect(b.runnerHash()).toBe(a.runnerHash());
    }
  });
  it('trace on/off and candidate score inspection do not perturb four-character decisions',()=>{const cfg=fighterConfig(content,18,'mirror','iron',300),a=new UtilityRunner(content,cfg,{settings,trace:true}),b=new UtilityRunner(content,cfg,{settings,trace:false});expect(a.run()).toEqual(b.run());expect(a.runnerHash()).toBe(b.runnerHash());expect(a.traces.every(t=>t.trace.aiVersion==='utility-v2')).toBe(true);for(const trace of a.traces)for(const candidate of trace.trace.candidates)if(candidate.outcome)expect(Number.isFinite(scoreOption(scene().c,candidate.option,candidate.outcome).Uraw)).toBe(true);});
});
