import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import type { ContentSource } from '../src/contracts/content-schema.js';
import type { Observation, FighterWorld } from '../src/contracts/fighter.js';
import type { CandidateTrace, OutcomeEstimate, Option } from '../src/contracts/ai.js';
import { compileUtilityContent } from '../src/content/utility.js';
import { initialFighterState, fighterWorldHash } from '../src/sim/fighter-state.js';
import { FighterSimulation } from '../src/sim/fighter.js';
import { fighterConfig } from '../src/runner/fighter.js';
import { UtilityRunner } from '../src/runner/utility.js';
import { ObservationBuffer } from '../src/runner/observation.js';
import { replayInputs } from '../src/runner/input-replay.js';
import { UtilityController } from '../src/ai/utility.js';
import { buildBelief } from '../src/ai/belief.js';
import { emptyMemory, emptyExecution, beginOwnResult, consumeMemory, adaptiveWeights, possibleBasicLikelihood, resultDeadline } from '../src/ai/memory.js';
import { generateOptions } from '../src/ai/options.js';
import { buildThreats, predictOutcome, predictionGrid, type PredictionContext } from '../src/ai/prediction.js';
import { scoreOutcome, scoreOption } from '../src/ai/score.js';
import { eligiblePool, choose, switchMargin } from '../src/ai/selection.js';
import { attributes } from '../src/ai/abilities.js';
import { advanceMotion } from '../src/ai/motion.js';
import { Xoshiro128ss } from '../src/math/random.js';
import { NEUTRAL_INTENT } from '../src/contracts/state.js';
const source = JSON.parse(readFileSync('content/fighter-phase2.json', 'utf8')) as ContentSource;
const diagnostic = structuredClone(source);
for (const p of diagnostic.profiles) {
    p.reactionDelayTicks = 0;
    p.positionNoisePx = 0;
    p.velocityNoisePxPerSecond = 0;
}
const content = compileUtilityContent(diagnostic), production = compileUtilityContent(source), settings = { noise: false, randomChoice: false, memory: true }, profile = content.source.profiles[0]!;
function scene(a = 'standard', b = 'standard', edit: (w: FighterWorld) => void = () => { }): {
    o: Observation;
    w: FighterWorld;
    c: PredictionContext;
} {
    const w = structuredClone(initialFighterState(fighterConfig(content, 17, a, b), content, 'phase2-v1')) as FighterWorld;
    w.entities[0].body.position.x = 400;
    w.entities[1].body.position.x = 480;
    edit(w);
    const buffer = new ObservationBuffer(content);
    buffer.push(w, [], []);
    const o = buffer.observe(w, 0), memory = emptyMemory(), execution = emptyExecution(), c: PredictionContext = { observation: o, content, profile, settings, memory, execution, belief: buildBelief(o, content, profile, memory, 17, settings) };
    return { o, w, c };
}
const opt = (kind: Option['kind'], moveX: -1 | 0 | 1 = 0, slot: Option['slot'] = null): Option => ({ key: `${kind}:${slot ?? ''}:${moveX}`, kind, moveX, slot, aimX: 1, legal: true, reason: null, tag: 'test' });
const outcome: OutcomeEstimate = { expectedDamageDealtPct: 0, meanDamageTakenPct: 0, worstDamageTakenPct: 0, killLikelihood: 0, deathLikelihood: 0, positionQualityBefore: 0, positionQualityAfter: 0, bandProgressPx:0, residualExposurePct: 0, setupValue: 0, confidence: 1, earlyRiskPct: 0, hitTicks: [], segmentsUsed: 5, budgetExceeded: false, setupConfidence: .6, setupReason: 'test' };
const candidate = (o: Option, score: number): CandidateTrace => ({ option: o, outcome, score: { ...scoreOutcome(outcome, profile, 1, 0, 0), Uraw: score }, eligible: false, switchMargin: 0 });
describe('Phase 2 perception, selection and exact score', () => {
    it('cold entry uses only self position, moves toward center and waits on arrival',()=>{const {o}=scene();const ctrl=new UtilityController(17,content,profile,settings);expect(ctrl.update({...o,opponent:null,sensedTick:null}).moveX).toBe(1);const atCenter={...o,opponent:null,sensedTick:null,self:{...o.self,entity:{...o.self.entity,body:{...o.self.entity.body,position:{x:448,y:32},facing:-1 as const}}}};expect(new UtilityController(17,content,profile,settings).update(atCenter)).toEqual(NEUTRAL_INTENT);const right={...atCenter,self:{...atCenter.self,entity:{...atCenter.self.entity,body:{...atCenter.self.entity.body,position:{x:700,y:32},facing:1 as const}}}};expect(new UtilityController(17,content,profile,settings).update(right).moveX).toBe(-1);});
    it('formula vector is 6.22, resource/death/recovery remain in HP-percentage scale', () => { const p = { ...profile, riskPreference: .5 }; expect(scoreOutcome({ ...outcome, expectedDamageDealtPct: 8.4, meanDamageTakenPct: 1.2, worstDamageTakenPct: 1.2, positionQualityAfter: .1 }, p, 1, .8, 0).Uraw).toBeCloseTo(6.22); expect(scoreOutcome({ ...outcome, deathLikelihood: 1 }, p, .1, 0, 0).X).toBe(18); });
    it('AI-18 all negative chooses best; all illegal returns neutral', () => { const options = [candidate(opt('move', -1), -3), candidate(opt('move', 1), -1)]; expect(choose(eligiblePool(options, null, false, false), .3, false)?.score?.Uraw).toBe(-1); const { o } = scene(); const ctrl = new UtilityController(17, content, profile, settings); expect(ctrl.update({ ...o, self: { ...o.self, canMove: false, canJump: false, legalSlots: [] } })).toEqual(NEUTRAL_INTENT); });
    it('cast margin is .35; threshold filtering precedes the near-best pool', () => { const cast = candidate(opt('cast', 0, 'ultimate'), 1), move = candidate(opt('move', 1), 1.3), jump = candidate(opt('jump'), .8), pool = eligiblePool([move, cast, jump], 0, false, false); expect(pool.map(c => c.option.kind)).toEqual(['cast', 'jump']); expect(switchMargin(cast.option, 0)).toBe(.35); expect(pool.every(c => c.score!.Uraw > c.switchMargin)).toBe(true); });
    it('AI-17 reversed candidate enumeration gives identical sorted pool and choice, band zero is deterministic', () => { const a = [candidate(opt('move', -1), 1), candidate(opt('move', 0), .9), candidate(opt('move', 1), 1)]; const p = eligiblePool(a, null, false, false), q = eligiblePool([...a].reverse(), null, false, false); expect(p.map(c => c.option.key)).toEqual(q.map(c => c.option.key)); expect(choose(p, .7, true)).toEqual(choose(q, .7, true)); expect(choose(p, .99, true, 0)!.score!.Uraw).toBe(1); });
    it('one RNG uint32 per decision; nondecision updates and trace reads draw nothing', () => { const { o } = scene(), ctrl = new UtilityController(17, content, profile, settings), rng = new Xoshiro128ss(17); ctrl.update(o); rng.nextUint32(); expect(ctrl.snapshot().rngState).toEqual(rng.snapshot()); for (let t = 1; t < 6; t++) {
        ctrl.update({ ...o, nowTick: t });
        void ctrl.lastTrace;
        expect(ctrl.snapshot().rngState).toEqual(rng.snapshot());
    } ctrl.update({ ...o, nowTick: 6 }); rng.nextUint32(); expect(ctrl.snapshot().rngState).toEqual(rng.snapshot()); });
    it('AI-04 current hidden enemy position/cooldown/projectile changes do not alter input before delay', () => { const config = fighterConfig(production), w = structuredClone(initialFighterState(config, production, 'phase2-v1')) as FighterWorld, a = new ObservationBuffer(production), b = new ObservationBuffer(production), ca = new UtilityController(17, production, production.source.profiles[0]!, settings), cb = new UtilityController(17, production, production.source.profiles[0]!, settings); a.push(w, [], []); b.push(w, [], []); for (let t = 1; t <= 8; t++) {
        const x = structuredClone(w);
        x.tick = t;
        const y = structuredClone(x);
        y.entities[1].body.position.x = 100;
        y.entities[1].cooldownReadyTick.basic = 900;
        y.projectiles = [{ id: 10, ownerId: 2, sourceCastId: 9, abilityId: 'standard-bolt', position: { x: 700, y: 40 }, velocity: { x: -720, y: 0 }, radius: 12, expiresTick: 100, reflectionCount: 0, ignoreOwnerUntilOutside: false, hit: { damage: 12, launchDeltaV: { x: 420, y: 220 }, hitstunTicks: 8, hitGroup: 'bolt' } }];
        a.push(x, [], []);
        b.push(y, [], []);
        expect(ca.update(a.observe(x, 0))).toEqual(cb.update(b.observe(y, 0)));
    } expect(ca.snapshot()).toEqual(cb.snapshot()); });
    it('joint options stay <=18, fixed movement casts are deduplicated, no jump+cast', () => { const { o, c } = scene('rubber', 'standard', w => w.entities[0].energy = 100), options = generateOptions(o, content, c.belief); expect(options.length).toBeLessThanOrEqual(18); expect(options.filter(p => p.slot === 'ultimate')).toHaveLength(1); expect(new Set(options.map(p => p.key)).size).toBe(options.length); });
    it('AI-08 cooldown and hitstun do not cache or send casts', () => { const { o } = scene('standard', 'standard', w => { for (const slot of ['basic', 'skill1', 'skill2', 'ultimate'] as const)
        w.entities[0].cooldownReadyTick[slot] = 100; }); const ctrl = new UtilityController(17, content, profile, settings); expect(ctrl.update(o).cast).toBeNull(); expect(ctrl.lastTrace!.candidates.filter(c => c.option.kind === 'cast').every(c => c.option.reason === 'cooldown' || c.option.reason === 'resource')).toBe(true); expect(ctrl.update({ ...o, nowTick: 6, self: { ...o.self, entity: { ...o.self.entity, action: { kind: 'hitstun', untilTick: 20 } }, canMove: false, canJump: false } })).toEqual(NEUTRAL_INTENT); });
    it('AI-09 small alternating direction scores cannot overcome hysteresis for 60 ticks', () => { let flips = 0, move = 1; for (let t = 0; t < 60; t += 6) {
        const candidates = [candidate(opt('move', -1), t % 12 === 0 ? 1.1 : 1), candidate(opt('move', 1), t % 12 === 0 ? 1 : 1.1)], pool = eligiblePool(candidates, 1, false, false), chosen = choose(pool, .5, false);
        if (chosen && chosen.option.moveX !== move) {
            move = chosen.option.moveX;
            flips++;
        }
    } expect(flips).toBeLessThanOrEqual(2); });
});
describe('Phase 2 geometric prediction and tactical scenarios', () => {
    it('mature major danger breaks move hold, but never scores faster than every three ticks', () => { const { o } = scene('rubber', 'standard', w => { w.entities[0].body.position.x = 220; w.entities[1].body.position.x = 700; }); const ctrl = new UtilityController(17, content, profile, settings); ctrl.update(o); const projectile = { id: 1, ownerId: 2, sourceCastId: 1, abilityId: 'standard-volley', position: { x: 365, y: 40 }, velocity: { x: -720, y: 0 }, radius: 12, reflectable: true }; expect(ctrl.update({ ...o, nowTick: 1, sensedTick: 1, projectiles: [projectile] }).requestId).toBeNull(); expect(ctrl.lastTrace).toBeNull(); const next = { ...projectile, id: 2 }; ctrl.update({ ...o, nowTick: 3, sensedTick: 3, projectiles: [next, { ...next, id: 3 }] }); expect(ctrl.lastTrace!.emergency).toBe(true); expect(ctrl.lastTrace!.nowTick).toBe(3); expect(ctrl.lastTrace!.input.jumpPressed || ctrl.lastTrace!.input.cast?.slot === 'skill2' || ctrl.lastTrace!.input.moveX === -1).toBe(true); });
    it.each([['basic', 80, true], ['basic', 300, false], ['skill1', 300, true], ['skill1', 80, true]] as const)('no-noise %s at %s matches real collision hit=%s', (slot, distance, hit) => { const { w, c } = scene('standard', 'standard', w => w.entities[1].body.position.x = 400 + distance); c.belief.hypotheses = c.belief.hypotheses.map(h => ({ ...h, moveX: 0 })); const expected = predictOutcome(c, opt('cast', 0, slot)), sim = new FighterSimulation(content, w.config, w, 'phase2-v1'); const events = [...sim.step([{ ...NEUTRAL_INTENT, cast: { slot, aimX: 1 }, requestId: 1 }, NEUTRAL_INTENT]).events]; for (let t = 1; t < 30; t++)
        events.push(...sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).events); expect(expected.expectedDamageDealtPct > 0).toBe(hit); expect(events.some(e => e.type === 'DamageResolved' && e.sourceId === 1)).toBe(hit); });
    it('AI-01 far melee-only moves into attack range within 3 seconds; empty swing scores lower', () => { const { o, w, c } = scene('rubber', 'standard', w => { w.entities[0].body.position.x = 220; w.entities[1].body.position.x = 700; w.entities[0].cooldownReadyTick.skill1 = 1000; w.entities[0].cooldownReadyTick.skill2 = 1000; }); c.profile = { ...profile, distancePreference: 'melee' }; const approach = predictOutcome(c, opt('move', 1)), swing = predictOutcome(c, opt('cast', 0, 'basic')); expect(scoreOption(c, opt('move', 1), approach).Uraw).toBeGreaterThan(scoreOption(c, opt('cast', 0, 'basic'), swing).Uraw); const ctrl = new UtilityController(17, content, c.profile, settings), sim = new FighterSimulation(content, w.config, w, 'phase2-v1'), buffer = new ObservationBuffer(content); buffer.push(w, [], []); let closest = Infinity; for (let t = 0; t < 180 && !sim.snapshot().result; t++) {
        const s = sim.snapshot(), input = ctrl.update(buffer.observe(s, 0)), out = sim.step([input, NEUTRAL_INTENT]);
        buffer.push(out.state, out.events, out.receipts);
        closest = Math.min(closest, Math.abs(out.state.entities[0].body.position.x - out.state.entities[1].body.position.x));
    } expect(closest).toBeLessThanOrEqual(135); expect(o.opponent).not.toBeNull(); });
    it.each([[200, true], [350, false]] as const)('dash-hit geometric estimate at %i agrees with physical damage=%s', (distance, hit) => { const { w, c } = scene('rubber', 'standard', w => w.entities[1].body.position.x = 400 + distance); c.belief.hypotheses = c.belief.hypotheses.map(h => ({ ...h, moveX: 0 })); const estimate = predictOutcome(c, opt('cast', 0, 'skill1')), sim = new FighterSimulation(content, w.config, w, 'phase2-v1'), events = [...sim.step([{ ...NEUTRAL_INTENT, cast: { slot: 'skill1', aimX: 1 }, requestId: 1 }, NEUTRAL_INTENT]).events]; for (let t = 1; t < 30; t++)
        events.push(...sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).events); expect(estimate.expectedDamageDealtPct > 0).toBe(hit); expect(events.some(e => e.type === 'DamageResolved' && e.sourceId === 1)).toBe(hit); });
    it('defense result links to its own guard cast; movement does not turn a locked cast', () => { const { w } = scene('rubber', 'standard', w => w.entities[1].body.position.x = 466), sim = new FighterSimulation(content, w.config, w, 'phase2-v1'), events = [...sim.step([{ ...NEUTRAL_INTENT, cast: { slot: 'skill2', aimX: 1 }, requestId: 1 }, NEUTRAL_INTENT]).events]; for (let t = 1; t < 6; t++)
        sim.step([{ ...NEUTRAL_INTENT, moveX: -1 }, NEUTRAL_INTENT]); expect(sim.snapshot().entities[0].body.facing).toBe(1); sim.step([NEUTRAL_INTENT, { ...NEUTRAL_INTENT, cast: { slot: 'basic', aimX: -1 }, requestId: 1 }]); for (let t = 0; t < 9; t++)
        events.push(...sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]).events); const prevented = events.find(e => e.type === 'DamagePrevented'); expect(prevented?.payload.castId).toBe(1); expect(sim.snapshot().entities[0].hp).toBeCloseTo(95.2); });
    it('AI-02 near recovery fast kill beats waiting and costly slow volley', () => { const { c } = scene('standard', 'standard', w => { w.tick = 18; w.entities[0].energy = 100; w.entities[1].hp = 8; w.entities[1].action = { kind: 'cast', castId: 1, requestId: 1, abilityId: 'standard-jab', startedTick: 0, startupTicks: 8, activeTicks: 4, recoveryTicks: 14 }; }); const jab = scoreOption(c, opt('cast', 0, 'basic'), predictOutcome(c, opt('cast', 0, 'basic'))).Uraw, wait = scoreOption(c, opt('move'), predictOutcome(c, opt('move'))).Uraw, slow = scoreOption(c, opt('cast', 0, 'ultimate'), predictOutcome(c, opt('cast', 0, 'ultimate'))).Uraw; expect(jab).toBeGreaterThan(wait); expect(jab).toBeGreaterThan(slow); });
    it('AI-03 departing target with old recovery tell is not automatically punished', () => { const { o, c } = scene('standard', 'standard', w => { w.entities[1].body.position.x = 800; w.entities[1].body.velocity.x = 800; }); const enemy = { ...o.opponent!, tell: { abilityId: 'standard-jab', phase: 'recovery' as const, visibleSinceTick: 0 } }; c.observation = { ...o, nowTick: 25, sensedTick: 25, opponent: enemy }; c.belief = buildBelief(c.observation, content, profile, c.memory, 17, settings); expect(predictOutcome(c, opt('cast', 0, 'basic')).expectedDamageDealtPct).toBe(0); expect(scoreOption(c, opt('cast', 0, 'basic'), predictOutcome(c, opt('cast', 0, 'basic'))).Uraw).toBeLessThan(scoreOption(c, opt('move', 1), predictOutcome(c, opt('move', 1))).Uraw); });
    it('AI-05 mature bolt makes jump/guard safer; guard too late earns no immunity', () => { const { o, c } = scene('rubber', 'standard', w => w.entities[1].body.position.x = 800); const bolt = { id: 1, ownerId: 2, sourceCastId: 1, abilityId: 'standard-bolt', position: { x: 540, y: 40 }, velocity: { x: -720, y: 0 }, radius: 12, reflectable: true }; c.observation = { ...o, projectiles: [bolt] }; const wait = predictOutcome(c, opt('move')), guard = predictOutcome(c, opt('cast', 0, 'skill2')), jump = predictOutcome(c, opt('jump')); expect(wait.meanDamageTakenPct).toBeGreaterThan(0); expect(guard.meanDamageTakenPct).toBeLessThan(wait.meanDamageTakenPct); expect(jump.meanDamageTakenPct).toBeLessThan(wait.meanDamageTakenPct); c.observation = { ...o, projectiles: [{ ...bolt, position: { x: 450, y: 40 } }] }; expect(predictOutcome(c, opt('cast', 0, 'skill2')).meanDamageTakenPct).toBeCloseTo(predictOutcome(c, opt('move')).meanDamageTakenPct); const ctrl = new UtilityController(17, content, profile, settings); const input = ctrl.update({ ...o, projectiles: [bolt] }); expect(input.jumpPressed || input.cast?.slot === 'skill2' || input.moveX !== 0).toBe(true); });
    it('AI-11 delayed high speed bounce advances at most 18 ticks and shares noise across candidates', () => { const { o, c } = scene('standard', 'rubber', w => { w.entities[1].body.position.x = 900; w.entities[1].body.velocity.x = 900; }); const belief = buildBelief({ ...o, nowTick: 12, sensedTick: 0 }, content, profile, c.memory, 17, settings); expect(belief.opponent!.velocity.x).toBeLessThan(0); expect(belief.opponent!.position.x).toBeLessThan(928); const old = buildBelief({ ...o, nowTick: 60, sensedTick: 0 }, content, { ...profile, reactionDelayTicks: 9 }, c.memory, 17, settings), cap = buildBelief({ ...o, nowTick: 18, sensedTick: 0 }, content, profile, c.memory, 17, settings); expect(old.opponent!.position).toEqual(cap.opponent!.position); expect(old.confidence).toBe(.5); const noisy = buildBelief(o, content, { ...profile, positionNoisePx: 6, velocityNoisePxPerSecond: 18 }, c.memory, 22, { ...settings, noise: true }); const before = structuredClone(noisy); for (const option of generateOptions(o, content, noisy))
        if (option.legal)
            predictOutcome({ ...c, belief: noisy }, option); expect(noisy).toEqual(before); });
    it('AI-12 low HP makes counter more sensitive to avoidable death than pressure', () => { const pressure = source.profiles.find(p => p.id === 'pressure')!, counter = source.profiles.find(p => p.id === 'counter')!, risk = { ...outcome, expectedDamageDealtPct: 10, meanDamageTakenPct: 6, worstDamageTakenPct: 12 }; expect(scoreOutcome(risk, counter, .1, 0, 0).wL).toBeGreaterThan(scoreOutcome(risk, pressure, .1, 0, 0).wL); expect(scoreOutcome(risk, counter, .1, 0, 0).Uraw).toBeLessThan(scoreOutcome(risk, pressure, .1, 0, 0).Uraw); });
    it('AI-13 death before strike removes kill reward and adds death cost', () => { const { o, c } = scene('standard', 'standard', w => { w.entities[0].hp = 4; w.entities[1].hp = 4; }); c.observation = { ...o, projectiles: [{ id: 1, ownerId: 2, sourceCastId: 1, abilityId: 'standard-bolt', position: { x: 460, y: 40 }, velocity: { x: -720, y: 0 }, radius: 12, reflectable: true }] }; const out = predictOutcome(c, opt('cast', 0, 'basic')); expect(out.deathLikelihood).toBe(1); expect(out.killLikelihood).toBe(0); expect(scoreOption(c, opt('cast', 0, 'basic'), out).X).toBe(18); });
    it('AI-14 buff has zero setup without wall opportunity; aged full energy can cross cast margin with opportunity', () => { const { o, c } = scene('rubber', 'standard', w => { w.tick = 600; w.entities[0].energy = 100; w.entities[0].body.position.x = 700; w.entities[0].body.velocity.x = 900; w.entities[1].body.position.x = 640; }); c.memory.ultimateReadySinceTick = 0; c.profile = { ...profile, resourcePatience: 0 }; const ultimate = opt('cast', 0, 'ultimate'), out = predictOutcome(c, ultimate); expect(out.setupValue).toBeGreaterThan(0); const wait = opt('move', 0), current = scoreOption(c, wait, predictOutcome(c, wait)).Uraw; expect(scoreOption(c, ultimate, out).Uraw - current).toBeGreaterThan(.35); c.observation = { ...o, self: { ...o.self, entity: { ...o.self.entity, body: { ...o.self.entity.body, velocity: { x: 0, y: 0 } } } } }; expect(predictOutcome(c, ultimate).setupValue).toBe(0); });
    it('AI-15 recovery outside H creates capped residual risk and inserted events stay within 12 segments', () => { const { c } = scene(); const push = opt('cast', 0, 'skill2'), out = predictOutcome(c, push); expect(out.residualExposurePct).toBeGreaterThan(0); expect(out.residualExposurePct).toBeLessThanOrEqual(12); const grid = predictionGrid(c, push, buildThreats(c)); expect(grid.ticks).toContain(16); expect(grid.ticks).toContain(21); expect(out.segmentsUsed).toBeLessThanOrEqual(12); });
    it('light motion matches a gravity arc without contacts', () => { const { o, w } = scene('standard', 'standard', w => { w.entities[0].body.position = { x: 300, y: 400 }; w.entities[0].body.velocity = { x: 200, y: 200 }; w.entities[0].body.grounded = false; }); const body = structuredClone(w.entities[0].body); advanceMotion(body, attributes(content, o.self.entity, 0), null, 6, o.arena); const sim = new FighterSimulation(content, w.config, w, 'phase2-v1'); for (let t = 0; t < 6; t++)
        sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(body.position.y).toBeCloseTo(sim.snapshot().entities[0].body.position.y, 8); });
});
describe('bounded memory, receipts and checkpoint continuation', () => {
    it('far parked controller crosses movement hysteresis only through bounded positive band progress',()=>{const {o}=scene('standard','standard',w=>{w.tick=90;w.entities[0].body.position.x=200;w.entities[1].body.position.x=800;w.entities[0].cooldownReadyTick.skill1=1000;w.entities[0].cooldownReadyTick.skill2=1000;});const ctrl=new UtilityController(17,content,profile,settings),s=structuredClone(ctrl.snapshot());s.memory.lastPositions=[{tick:0,position:{x:200,y:32},grounded:true}];s.execution.optionKey='move:wait:0';s.execution.moveX=0;s.execution.minimumHoldUntilTick=6;ctrl.restore(s);expect(ctrl.update(o).moveX).toBe(1);const picked=ctrl.lastTrace!.candidates.find(c=>c.option.key===ctrl.lastTrace!.selectedKey)!;expect(picked.score!.stuckBonus).toBe(2);expect(picked.outcome!.bandProgressPx).toBeGreaterThan(20);});
    it('aged full-energy buff actually executes with opportunity and stays unused without one', () => {
        const {o}=scene('rubber','standard',w=>{w.tick=600;w.entities[0].energy=100;w.entities[0].body.position.x=700;w.entities[0].body.velocity.x=900;w.entities[1].body.position.x=640;});
        const p={...profile,resourcePatience:0},controller=new UtilityController(17,content,p,settings),saved=structuredClone(controller.snapshot());saved.memory.ultimateReadySinceTick=0;controller.restore(saved);
        const observation={...o,self:{...o.self,legalSlots:['ultimate' as const],canJump:false}};
        expect(controller.update(observation).cast?.slot).toBe('ultimate');
        const other=new UtilityController(17,content,p,settings);other.restore(saved);
        expect(other.update({...observation,self:{...observation.self,entity:{...o.self.entity,body:{...o.self.entity.body,velocity:{x:0,y:0}}}}}).cast?.slot).not.toBe('ultimate');
    });
    it('floor-supported body collision does not chatter at time zero or exhaust diagnostics', () => { const { w } = scene('standard', 'standard', w => { w.entities[0].body.position = { x: 724.3925662033125, y: 32 }; w.entities[1].body.position = { x: 714.4781575968201, y: 95.23860266654724 }; w.entities[1].body.velocity = { x: -55.19222657604914, y: -82.93848448874259 }; w.entities[1].body.grounded = false; }); const sim = new FighterSimulation(content, w.config, w, 'phase2-v1'); for (let t = 0; t < 60; t++)
        sim.step([NEUTRAL_INTENT, NEUTRAL_INTENT]); expect(sim.snapshot().diagnostics).toEqual([]); expect(sim.snapshot().result).toBeNull(); expect(sim.snapshot().entities[0].body.position.y).toBeGreaterThanOrEqual(32); });
    it('AI-16 fewer than four encounters cannot adapt, posterior changes stay bounded and memory switch disables it', () => { const m = emptyMemory(); for (let i = 0; i < 3; i++)
        m.encounters.push({ startedTick: i * 60, completedTick: i * 60 + 12, context: 'near-ground', outcome: 'basic' }); expect(adaptiveWeights(m, 'near-ground', true).adapted).toBe(false); expect(possibleBasicLikelihood(m, 'near-ground', true)).toBe(.35); m.encounters.push({ startedTick: 180, completedTick: 192, context: 'near-ground', outcome: 'basic' }); expect(adaptiveWeights(m, 'near-ground', true).adapted).toBe(true); expect(Math.abs(possibleBasicLikelihood(m, 'near-ground', true) - .35)).toBeLessThanOrEqual(.15 + 1e-12); expect(adaptiveWeights(m, 'near-ground', false).weights).toEqual([.5, .25, .25]); });
    it('encounter is independent, first event at entry is counted, no other outcome before sensed deadline', () => { const { o } = scene(); const m = emptyMemory(), e = emptyExecution(); m.lastDistance = 200; m.insideBand = false; const entry = { ...o, nowTick: 12, sensedTick: 0, visibleEvents: [{ seq: 1, sourceTick: 0, sourceId: 2, targetId: null, detail: { kind: 'cast' as const, castId: 1, abilityId: 'standard-jab', slot: 'basic' as const } }] }; consumeMemory(m, e, entry, content, profile, settings, [60, 120]); expect(m.encounters[0]?.outcome).toBe('basic'); m.insideBand = false; m.lastDistance = 200; consumeMemory(m, e, { ...o, nowTick: 100, sensedTick: 10, visibleEvents: [] }, content, profile, settings, [60, 120]); expect(m.encounters).toHaveLength(1); m.lastEncounterStartedTick = -45; m.insideBand = false; consumeMemory(m, e, { ...o, nowTick: 100, sensedTick: 20, visibleEvents: [] }, content, profile, settings, [60, 120]); expect(m.pendingEncounter).not.toBeNull(); expect(m.encounters).toHaveLength(1); consumeMemory(m, e, { ...o, nowTick: 110, sensedTick: 49, visibleEvents: [] }, content, profile, settings, [60, 120]); expect(m.encounters).toHaveLength(1); consumeMemory(m, e, { ...o, nowTick: 111, sensedTick: 50, visibleEvents: [] }, content, profile, settings, [60, 120]); expect(m.encounters.at(-1)?.outcome).toBe('other'); });
    it('accepted and interrupted in the same receipt array are both consumed exactly once', () => { const { o } = scene(), m = emptyMemory(), e = emptyExecution(); beginOwnResult(m, o, content, profile, 'basic', 1, 1); e.activeRequestId = 1; e.activeSlot = 'basic'; const receipts = [{ receiptSeq: 1, entityId: 1, requestId: 1, tick: 0, result: 'accepted' as const, reason: 'ok' as const }, { receiptSeq: 2, entityId: 1, requestId: 1, tick: 0, result: 'interrupted' as const, reason: 'hitstun' as const }]; consumeMemory(m, e, { ...o, self: { ...o.self, receipts } }, content, profile, settings, [60, 120]); expect(e.lastReceiptSeq).toBe(2); expect(e.activeRequestId).toBeNull(); expect(m.pendingOwnResults[0]!.accepted).toBe(true); expect(m.pendingOwnResults[0]!.finished).toBe(true); });
    it('pending projectile/volley result survives restore and is not a miss while in flight', () => { const { o } = scene(), a = new UtilityController(17, content, profile, settings), s = structuredClone(a.snapshot()); beginOwnResult(s.memory, o, content, profile, 'ultimate', 1, 1); s.memory.pendingOwnResults[0]!.accepted = true; const b = new UtilityController(18, content, profile, settings); b.restore(s); b.update({ ...o, nowTick: 60, sensedTick: 60 }); expect(b.snapshot().memory.pendingOwnResults.some(p => p.slot === 'ultimate')).toBe(true); expect(b.snapshot().memory.recentOwnResults).toEqual([]); expect(resultDeadline(content, 'standard', 'ultimate', 0, 9).resultDueTick).toBeGreaterThan(100); });
    it('AI-10 wall push receives cost after 30 ticks, stuck approach bonus is capped at two', () => { const { o, c } = scene('standard', 'standard', w => { w.entities[0].body.position.x = 32; w.entities[1].body.position.x = 600; }); c.execution.moveX = -1; for (let t = 0; t <= 90; t++)
        consumeMemory(c.memory, c.execution, { ...o, nowTick: t, sensedTick: t }, content, profile, settings, [60, 120]); expect(c.memory.blockedMoveX).toBe(-1); expect(c.memory.stuckUntilTick).toBeGreaterThan(90); c.observation = { ...o, nowTick: 90 }; const wall = scoreOption(c, opt('move', -1), predictOutcome(c, opt('move', -1))), approach = scoreOption(c, opt('move', 1), predictOutcome(c, opt('move', 1))); expect(wall.wallCost).toBe(2); expect(approach.stuckBonus).toBeLessThanOrEqual(2); expect(approach.Uraw).toBeGreaterThan(wall.Uraw); });
    it('AI-19 holds send trigger once, trace off has identical inputs/events and replay works', () => { const config = fighterConfig(production, 17, 'standard', 'rubber', 360), a = new UtilityRunner(production, config, { trace: true, recordFrames: false }), b = new UtilityRunner(production, config, { trace: false, recordFrames: false }); const x = a.run(), y = b.run(); expect(x).toEqual(y); expect(a.controllers.map(c => c.snapshot())).toEqual(b.controllers.map(c => c.snapshot())); expect(a.traces.length).toBeGreaterThan(10); for (const index of [0, 1] as const) {
        const ids = x.inputs.map(i => i.intents[index].requestId).filter(i => i !== null);
        expect(new Set(ids).size).toBe(ids.length);
    } expect(replayInputs(x, false).replay.finalWorldHash).toBe(x.finalWorldHash); }, 30000);
    it.each([120, 240, 359])('full checkpoint at %i resumes identical input, world, events, runner hash', tick => { const config = fighterConfig(production, 18, 'standard', 'rubber', 360), a = new UtilityRunner(production, config, { recordFrames: false }), b = new UtilityRunner(production, config, { recordFrames: false }); for (let i = 0; i < tick; i++)
        a.step(); const cp = JSON.parse(JSON.stringify(a.snapshot(true))); b.restore(cp); expect(b.runnerHash()).toBe(a.runnerHash()); while (!a.sim.snapshot().result) {
        a.step();
        b.step();
        expect(b.inputs.at(-1)).toEqual(a.inputs.at(-1));
        expect(fighterWorldHash(b.sim.snapshot())).toBe(fighterWorldHash(a.sim.snapshot()));
    } expect(b.events).toEqual(a.events); expect(b.runnerHash()).toBe(a.runnerHash()); expect(b.replay()).toEqual(a.replay()); }, 30000);
    it('tampered checkpoint and wrong content are rejected', () => { const config = fighterConfig(production, 17, 'standard', 'rubber', 30), a = new UtilityRunner(production, config, { recordFrames: false }); a.step(); const cp = structuredClone(a.snapshot()); cp.nextTick++; expect(() => a.restore(cp)).toThrow(/runnerHash/); expect(() => new UtilityRunner(content, fighterConfig(content, 17, 'standard', 'rubber', 30)).restore(a.snapshot())).toThrow(/config/); });
});
