import { resolve } from 'node:path';
import { existsSync } from 'node:fs';
import { performance } from 'node:perf_hooks';
import { mkdir, rename, unlink } from 'node:fs/promises';
import { chromium } from 'playwright';
import { compilePhase3BContent } from '../content/phase3b.js';
import { rebuildPresentation } from '../runner/record-match.js';
import { RenderJobSchema, FrameIndexSchema, type FrameIndex, type RenderJob, type BatchTask } from '../contracts/production.js';
import { createRenderJob } from '../render/timeline.js';
import { audioPlan, mixAudio, pcmWav, SOUND_SPECS, AUDIO_ASSETS_VERSION } from '../render/audio.js';
import { hashCanonical } from '../math/hash.js';
import { canonicalSerialize } from '../math/canonical.js';
import { atomicJSON, atomicWrite, readJSON, safeRead, containedPath, fileHash } from './files.js';
import { loadReplayPackage, saveReplayPackage } from './replay-store.js';
import { type JobContext, failure } from './batch.js';
import { acquireJobLock } from './lock.js';
import { serveStatic } from './static-server.js';
import { preflight, command, verifyMP4, checkDisk, chromiumPath } from './media.js';
export interface ExportOptions {onlyIds?:string[];templateId?:'arena-dark'|'arena-light';preset?:'vertical-1080'|'vertical-720';}
const frameName=(n:number)=>`frame-${String(n).padStart(6,'0')}.png`;
interface VerificationIdentity {sha256:string;jobHash:string;sourceFrameIndexHash:string;audioWavHash:string;}
interface CleanupRecord {status:string;preHash:string;postHash?:string;}
async function validateStoredInputs(directory:string,job:RenderJob,record:VerificationIdentity){const index=FrameIndexSchema.parse(await readJSON(resolve(directory,'frame-index.json'))),indexHash=fileHash(await safeRead(directory,'frame-index.json'));if(index.jobId!==job.id||index.frameCount!==job.totalFrames||index.hashes.length!==job.totalFrames||index.hashes.some(h=>h===null))throw new Error('COMPLETED_FRAME_INDEX_MISMATCH');
  let cleanup:CleanupRecord|null=null;if(existsSync(resolve(directory,'cleanup.json')))cleanup=await readJSON(resolve(directory,'cleanup.json')) as CleanupRecord;
  if(cleanup&&cleanup.preHash!==record.sourceFrameIndexHash)throw new Error('CLEANUP_SOURCE_HASH_MISMATCH');
  if(index.cleaned){const originalHash=fileHash(Buffer.from(canonicalSerialize({...index,cleaned:false})+'\n'));if(originalHash!==record.sourceFrameIndexHash||!cleanup||!['running','complete'].includes(cleanup.status)||cleanup.status==='complete'&&cleanup.postHash!==indexHash)throw new Error('CLEANUP_HASH_MISMATCH');}else{if(indexHash!==record.sourceFrameIndexHash)throw new Error('COMPLETED_SOURCE_INDEX_HASH_MISMATCH');if(cleanup?.status!=='running')for(let n=0;n<job.totalFrames;n++){const bytes=await safeRead(resolve(directory,'frames'),frameName(n));validatePNG(bytes,job);if(fileHash(bytes)!==index.hashes[n])throw new Error('COMPLETED_PNG_HASH_MISMATCH '+n);}}
  if(fileHash(await safeRead(directory,'audio.wav'))!==record.audioWavHash)throw new Error('COMPLETED_AUDIO_HASH_MISMATCH');return index;
}
async function cleanVerifiedFrames(directory:string,index:FrameIndex,expectedHash:string){if(!index.cleaned){await atomicJSON(resolve(directory,'cleanup.json'),{status:'running',preHash:expectedHash});const framesDir=resolve(directory,'frames');for(let n=0;n<index.frameCount;n++)await unlink(containedPath(framesDir,frameName(n))).catch(error=>{if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;});index.cleaned=true;await atomicJSON(resolve(directory,'frame-index.json'),index);}await atomicJSON(resolve(directory,'cleanup.json'),{status:'complete',preHash:expectedHash,postHash:fileHash(await safeRead(directory,'frame-index.json'))});}
function validatePNG(bytes:Buffer,job:RenderJob){if(bytes.length<24||bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||bytes.readUInt32BE(16)!==job.width||bytes.readUInt32BE(20)!==job.height)throw new Error('PNG_DIMENSIONS_OR_SIGNATURE');}
async function stage(context:JobContext,task:BatchTask,state:BatchTask['state']){task.state=state;await context.save();if(context.cancelled())throw new Error('CANCELLED');}
async function inject(context:JobContext,stageName:JobContext['fault']):Promise<boolean>{const path=resolve(context.directory,`fault-${stageName}.json`);if(context.fault!==stageName||existsSync(path))return false;await atomicJSON(path,{stage:stageName,task:context.batch.selection[0],injectedAt:new Date().toISOString()});return true;}
async function rebuild(context:JobContext,task:BatchTask){const directory=resolve(context.directory,'matches',task.matchId),pkg=await loadReplayPackage(directory);if(pkg.frames.length&&(!context.batch.config.fullCheckpoints||pkg.checkpoints.length))return pkg;
  await stage(context,task,'rebuilding-track');const content=compilePhase3BContent(pkg.content),result=rebuildPresentation(content,pkg.replay,pkg.hashes,pkg.manifest.runner,context.batch.config.fullCheckpoints,context.cancelled);
  if(await inject(context,'rebuilding-track')){await atomicWrite(resolve(directory,'interrupted-track.tmp'),'incomplete uncommitted track');throw new Error('INJECTED_REBUILD_FAILURE');}
  await saveReplayPackage(directory,{replay:pkg.replay,content,runner:pkg.manifest.runner,hashes:pkg.hashes,analysis:pkg.analysis,toolchainId:pkg.manifest.toolchainId,rulesHash:pkg.manifest.rulesHash,frames:result.frames,...(context.batch.config.fullCheckpoints?{checkpoints:result.checkpoints}:{}),beforeManifest:async newHash=>atomicJSON(resolve(directory,'rebuild-journal.json'),{matchId:task.matchId,oldHash:task.manifestHash,newHash})});
  task.manifestHash=fileHash(await safeRead(directory,'manifest.json'));task.state='ready-to-render';task.lastCompleteState='ready-to-render';await context.save();return loadReplayPackage(directory);
}
async function renderOne(context:JobContext,task:BatchTask,tools:Awaited<ReturnType<typeof preflight>>,options:ExportOptions){const started=performance.now();let captureMs=0,encodingMs=0;const pkg=await rebuild(context,task),job=createRenderJob(pkg.manifest,task.manifestHash!,{preset:options.preset??context.batch.config.preset,templateId:options.templateId??context.batch.config.templateId,fontHash:tools.font.sha256,audioAssetsHash:hashCanonical({version:AUDIO_ASSETS_VERSION,specs:SOUND_SPECS}),keepFrames:context.batch.config.keepFrames,toolchainId:tools.id}),directory=resolve(context.directory,'exports',job.id),framesDir=resolve(directory,'frames'),rebuildMs=performance.now()-started;
  await mkdir(framesDir,{recursive:true});task.exportId=job.id;task.totalFrames=job.totalFrames;await context.save();const jobPath=resolve(directory,'render-job.json');
  if(existsSync(jobPath)&&hashCanonical(RenderJobSchema.parse(await readJSON(jobPath)))!==hashCanonical(job))throw new Error('RENDER_JOB_IDENTITY_MISMATCH');await atomicJSON(jobPath,job);await atomicJSON(resolve(directory,'disk-budget.json'),await checkDisk(directory,job));
  const finalPath=resolve(directory,'video.mp4'),verifiedPath=resolve(directory,'verification.json');if(existsSync(finalPath)&&existsSync(verifiedPath)){const verified=await readJSON(verifiedPath) as VerificationIdentity;if(verified.sha256!==fileHash(await safeRead(directory,'video.mp4'))||verified.jobHash!==hashCanonical(job))throw new Error('COMPLETED_VIDEO_HASH_MISMATCH');const index=await validateStoredInputs(directory,job,verified);await verifyMP4(finalPath,job,tools,context.cancelled);if(!job.keepFrames)await cleanVerifiedFrames(directory,index,verified.sourceFrameIndexHash);task.state='complete';task.lastCompleteState='complete';task.framesComplete=job.totalFrames;await context.save();return;}
  let index:FrameIndex={schemaVersion:1,jobId:job.id,frameCount:job.totalFrames,hashes:Array.from({length:job.totalFrames},()=>null),cleaned:false};const indexPath=resolve(directory,'frame-index.json');if(existsSync(indexPath)){index=FrameIndexSchema.parse(await readJSON(indexPath));if(index.jobId!==job.id||index.frameCount!==job.totalFrames||index.hashes.length!==job.totalFrames||index.cleaned)throw new Error('FRAME_INDEX_MISMATCH');}
  let firstBad=0;for(;firstBad<job.totalFrames;firstBad++){const name=frameName(firstBad);if(!index.hashes[firstBad]||!existsSync(resolve(framesDir,name)))break;try{const bytes=await safeRead(framesDir,name);validatePNG(bytes,job);if(fileHash(bytes)!==index.hashes[firstBad])break;}catch{break;}}
  index.hashes.fill(null,firstBad);task.framesComplete=firstBad;await atomicJSON(indexPath,index);await stage(context,task,'rendering');
  if(firstBad<job.totalFrames){const payload={manifest:pkg.manifest,content:pkg.content,frames:pkg.frames,events:pkg.replay.events,job},server=await serveStatic(0,async(req,res)=>{if(req.url!=='/payload.json')return false;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(payload));return true;}),browser=await chromium.launch({headless:true,executablePath:chromiumPath()});
    try{const page=await browser.newPage({viewport:{width:job.width,height:job.height},deviceScaleFactor:1});await page.goto(server.url+'/export.html');await page.waitForFunction('globalThis.__videoExporter?.ready===true');await page.evaluate("fetch('/payload.json').then(r=>r.json()).then(p=>globalThis.__videoExporter.load(p))");const bounds=await page.locator('#video').boundingBox();if(!bounds||bounds.x!==0||bounds.y!==0||bounds.width!==job.width||bounds.height!==job.height)throw new Error('EXPORT_CANVAS_BOUNDS');const cdp=await page.context().newCDPSession(page);
      for(let n=firstBad;n<job.totalFrames;n++){if(context.cancelled())throw new Error('CANCELLED');const captureStarted=performance.now();await page.evaluate(`globalThis.__videoExporter.renderFrame(${n})`);const screenshot=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,clip:{x:0,y:0,width:job.width,height:job.height,scale:1}}),png=Buffer.from(screenshot.data,'base64');captureMs+=performance.now()-captureStarted;validatePNG(png,job);await atomicWrite(resolve(framesDir,frameName(n)),png);index.hashes[n]=fileHash(png);task.framesComplete=n+1;
        if(n%10===0||n===job.totalFrames-1){await atomicJSON(indexPath,index);await context.save();}if(n%120===0)console.log(`Frames ${job.id}: ${n+1}/${job.totalFrames}`);
        if(n===24&&await inject(context,'rendering'))throw new Error('INJECTED_SCREENSHOT_FAILURE');}
    }finally{await browser.close();await server.close();}}
  await atomicJSON(indexPath,index);
  for(let n=0;n<job.totalFrames;n++){const bytes=await safeRead(framesDir,frameName(n));validatePNG(bytes,job);if(fileHash(bytes)!==index.hashes[n])throw new Error('SOURCE_FRAME_HASH_MISMATCH '+n);}
  const cues=audioPlan(job,pkg.replay.events,pkg.content.arenas.find(a=>a.id===pkg.manifest.config.arenaId)!.width),mix=mixAudio(job,cues),wav=pcmWav(mix.samples);await atomicWrite(resolve(directory,'audio.wav'),wav);await atomicJSON(resolve(directory,'audio-plan.json'),{version:AUDIO_ASSETS_VERSION,assetsHash:job.audioAssetsHash,specs:SOUND_SPECS,cues,frames:mix.frames,peak:mix.peak,sampleRate:48000,channels:2,wavHash:fileHash(wav),source:'Self-created sine sweeps; src/render/audio.ts'});
  const candidate=resolve(directory,'candidate.mp4'),encodingRecordPath=resolve(directory,'encoding.json');let encoded=false;
  if(existsSync(candidate)&&existsSync(encodingRecordPath)){const record=await readJSON(encodingRecordPath) as {jobHash:string;sha256:string};encoded=record.jobHash===hashCanonical(job)&&record.sha256===fileHash(await safeRead(directory,'candidate.mp4'));}
  if(!encoded){await stage(context,task,'encoding');const fault=await inject(context,'encoding'),args=['-nostdin','-hide_banner','-loglevel','error','-y','-framerate','60','-start_number','0','-i',resolve(framesDir,'frame-%06d.png'),'-i',resolve(directory,'audio.wav'),'-map','0:v:0','-map','1:a:0','-frames:v',String(job.totalFrames),'-c:v','libx264','-preset','medium','-crf','20','-threads','4','-pix_fmt','yuv420p','-r','60','-c:a','aac','-ar','48000','-b:a','192k','-t',(job.totalFrames/60).toFixed(9),'-movflags','+faststart',candidate];
    const encodingStarted=performance.now();await command(resolve(tools.ffmpeg.path),args,{cancelled:context.cancelled,...(fault?{crashAfterMs:500}:{})});encodingMs=performance.now()-encodingStarted;await atomicJSON(encodingRecordPath,{jobHash:hashCanonical(job),sha256:fileHash(await safeRead(directory,'candidate.mp4')),args});}
  await stage(context,task,'verifying');if(await inject(context,'verifying'))throw new Error('INJECTED_VERIFICATION_INTERRUPTION');const verified=await verifyMP4(candidate,job,tools,context.cancelled);
  const battle=job.timeline.find(t=>t.kind==='battle')!,sampleFrames={intro:30,mid:battle.startFrame+Math.floor(pkg.manifest.durationTicks/2),ko:battle.endFrameExclusive-1,end:job.totalFrames-1};await mkdir(resolve(directory,'samples'),{recursive:true});
  for(const [name,n]of Object.entries(sampleFrames))await command(resolve(tools.ffmpeg.path),['-nostdin','-v','error','-y','-i',candidate,'-vf',`select='eq(n,${n})'`,'-frames:v','1',resolve(directory,'samples',name+'.png')],{cancelled:context.cancelled});
  const sha256=fileHash(await safeRead(directory,'candidate.mp4'));await atomicJSON(verifiedPath,{...verified,sha256,jobHash:hashCanonical(job),sourceFrameIndexHash:fileHash(await safeRead(directory,'frame-index.json')),audioWavHash:fileHash(wav),audioPeak:mix.peak,sampleFrames,toolchain:tools.id});await rename(candidate,finalPath);
  await atomicJSON(resolve(directory,'export-performance.json'),{schemaVersion:1,jobId:job.id,captureMethod:'playwright-cdp-surface-png-v1',rebuildMs,captureMs,encodingMs,otherMs:performance.now()-started-rebuildMs-captureMs-encodingMs,totalMs:performance.now()-started,renderedFrames:job.totalFrames-firstBad,reusedFrames:firstBad,reusedEncoding:encoded,videoSeconds:job.totalFrames/60,trace:false});
  task.state='complete';task.lastCompleteState='complete';task.framesComplete=job.totalFrames;await context.save();console.log(`Verified video: ${finalPath}`);
  if(!job.keepFrames)await cleanVerifiedFrames(directory,index,fileHash(await safeRead(directory,'frame-index.json')));
}
export async function renderSelection(context:JobContext,options:ExportOptions={}){const selection=options.onlyIds??context.batch.selection;if(!selection.length){context.batch.status='failed';await context.save();return;}if(selection.some(id=>!context.batch.tasks.some(t=>t.matchId===id&&t.manifestHash)))throw new Error('UNKNOWN_EXPORT_MATCH');const globalDir=resolve('artifacts','.export-lock');await mkdir(globalDir,{recursive:true});const unlock=await acquireJobLock(globalDir);
  try{let tools:Awaited<ReturnType<typeof preflight>>;try{tools=await preflight();}catch(error){await failure(context,context.batch.tasks.find(t=>t.matchId===selection[0])!,'preflight',error);context.batch.status='failed';await context.save();return;}for(const id of selection){if(context.cancelled())break;const task=context.batch.tasks.find(t=>t.matchId===id)!;try{await renderOne(context,task,tools,options);}catch(error){if(context.cancelled()||(error instanceof Error&&error.message==='CANCELLED')){task.state=task.lastCompleteState;context.batch.status='cancelled';await context.save();break;}await failure(context,task,task.state,error);}}
    context.batch.status=context.cancelled()?'cancelled':context.batch.selection.every(id=>context.batch.tasks.find(t=>t.matchId===id)?.state==='complete')?'complete':'failed';await context.save();
  }finally{await unlock();}
}
export async function verifySelection(context:JobContext){const tools=await preflight();for(const id of context.batch.selection){const task=context.batch.tasks.find(t=>t.matchId===id)!;if(!task.exportId)throw new Error('VIDEO_NOT_EXPORTED');const directory=resolve(context.directory,'exports',task.exportId),job=RenderJobSchema.parse(await readJSON(resolve(directory,'render-job.json'))),record=await readJSON(resolve(directory,'verification.json')) as VerificationIdentity;if(record.sha256!==fileHash(await safeRead(directory,'video.mp4'))||record.jobHash!==hashCanonical(job)||job.replayManifestHash!==task.manifestHash)throw new Error('VIDEO_OR_JOB_HASH_MISMATCH');await validateStoredInputs(directory,job,record);await verifyMP4(resolve(directory,'video.mp4'),job,tools,context.cancelled);}}
