import { resolve, relative } from 'node:path';
import { mkdir, readdir } from 'node:fs/promises';
import { existsSync, createWriteStream, createReadStream } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { spawn, type ChildProcess } from 'node:child_process';
import type { IncomingMessage } from 'node:http';
import { ProductionConfigSchema, BatchManifestSchema, ReplayManifestSchema, type ProductionConfig } from '../contracts/production.js';
import { compilePhase3BContent } from '../content/phase3b.js';
import { rebuildPresentation } from '../runner/record-match.js';
import { loadReplayPackage } from './replay-store.js';
import { containedPath, readJSON, atomicJSON, atomicWrite, safeRead, fileHash } from './files.js';
import { serveStatic } from './static-server.js';
import { openBatch } from './batch.js';
const artifacts=resolve('artifacts'),token=randomUUID();let active:{directory:string;process:ChildProcess}|null=null;
async function body(request:IncomingMessage){let size=0;const chunks:Buffer[]=[];for await(const chunk of request){size+=chunk.length;if(size>64*1024*1024)throw new Error('REQUEST_BUDGET_EXCEEDED');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;}
const directory=(path:unknown)=>{if(typeof path!=='string')throw new Error('Batch path required');return containedPath(artifacts,resolve(path));};
async function launch(dir:string,args:string[]){if(active)throw new Error('ANOTHER_TASK_RUNNING');await mkdir(dir,{recursive:true});const log=createWriteStream(resolve(dir,'production.log'),{flags:'a'}),child=spawn(process.execPath,[resolve('dist/node/cli/production.js'),...args],{stdio:['ignore','pipe','pipe'],windowsHide:true,cwd:resolve('.')});active={directory:dir,process:child};child.stdout?.pipe(log);child.stderr?.pipe(log);child.on('close',()=>{log.end();if(active?.process===child)active=null;});child.on('error',error=>{log.write(String(error));if(active?.process===child)active=null;});}
async function listJobs(root:string,depth=0):Promise<{path:string;batchId:string;status:string}[]>{if(depth>5)return[];const entries=await readdir(root,{withFileTypes:true}).catch(()=>[]),result=[];if(entries.some(e=>e.name==='batch.json')){try{const batch=BatchManifestSchema.parse(await readJSON(resolve(root,'batch.json')));result.push({path:root,batchId:batch.batchId,status:batch.status});}catch{}return result;}for(const entry of entries)if(entry.isDirectory()&&!entry.isSymbolicLink()&&!entry.name.startsWith('.'))result.push(...await listJobs(resolve(root,entry.name),depth+1));return result;}
async function importReplay(files:unknown,templateId:'arena-dark'|'arena-light'){if(!Array.isArray(files)||files.length<7||files.length>9)throw new Error('INVALID_IMPORTED_FILES');const manifestFile=files.find(f=>f.path==='manifest.json');if(!manifestFile||typeof manifestFile.base64!=='string')throw new Error('IMPORTED_MANIFEST_REQUIRED');const manifestBytes=Buffer.from(manifestFile.base64,'base64'),manifest=ReplayManifestSchema.parse(JSON.parse(manifestBytes.toString('utf8'))),id='import-'+fileHash(manifestBytes).slice(0,24),dir=resolve(artifacts,'imports',id),matchDir=resolve(dir,'matches',manifest.replayId);if(existsSync(resolve(dir,'batch.json')))return dir;
  await mkdir(matchDir,{recursive:true});const expected=new Map(manifest.files.map(f=>[f.path,f]));if(new Set(files.map(f=>f.path)).size!==files.length)throw new Error('DUPLICATE_IMPORTED_PATH');for(const file of files){if(typeof file.path!=='string'||typeof file.base64!=='string')throw new Error('INVALID_IMPORTED_FILE');const bytes=Buffer.from(file.base64,'base64'),entry=expected.get(file.path);if(file.path!=='manifest.json'&&(!entry||entry.bytes!==bytes.length||entry.sha256!==fileHash(bytes)))throw new Error('IMPORTED_FILE_HASH_MISMATCH');await atomicWrite(containedPath(matchDir,file.path),bytes);}
  const pkg=await loadReplayPackage(matchDir);if(!pkg.frames.length||!pkg.analysis.eligible)throw new Error('IMPORTED_EXPORT_REQUIRES_ELIGIBLE_SAVED_TRACK');const config=ProductionConfigSchema.parse({schemaVersion:1,aiVersion:manifest.aiVersion,id,output:relative(resolve('.'),dir),seed:manifest.seed,matchups:[{a:manifest.config.participants[0].characterId,b:manifest.config.participants[1].characterId}],countPerMatchup:1,workers:1,top:1,pacing:manifest.config.pacing.mode,preset:'vertical-1080',templateId,keepFrames:true,fullCheckpoints:false,maxTicks:manifest.config.maxTicks}),now=new Date().toISOString();await atomicJSON(resolve(dir,'batch.json'),BatchManifestSchema.parse({schemaVersion:1,batchId:id,createdAt:now,updatedAt:now,status:'ranked',config,engineBuild:'phase3b-v1',aiVersion:manifest.aiVersion,rulesHash:manifest.rulesHash,contentHash:manifest.contentHash,scoreVersion:'interesting-v1',toolchainId:manifest.toolchainId,workerCount:1,tasks:[{matchId:manifest.replayId,config:manifest.config,state:'ready-to-render',lastCompleteState:'ready-to-render',attempts:1,manifestHash:fileHash(manifestBytes),score:pkg.analysis.score,selectionReason:'imported-saved-track',exportId:null,framesComplete:0,totalFrames:0,failures:[]}],selection:[manifest.replayId],rankingHash:null,failures:[]}));return dir;
}
export async function startProductionServer(port=5177){await mkdir(artifacts,{recursive:true});const server=await serveStatic(port,async(request,response)=>{const url=new URL(request.url??'/','http://127.0.0.1');if(!url.pathname.startsWith('/api/'))return false;const send=(value:unknown,code=200)=>{response.statusCode=code;response.setHeader('Content-Type','application/json; charset=utf-8');response.end(JSON.stringify(value));};try{
  if(request.method==='POST'){if(request.headers['x-production-token']!==token||request.headers.origin&&request.headers.origin!==`http://127.0.0.1:${port}`)throw new Error('LOCAL_REQUEST_TOKEN_REQUIRED');const input=await body(request);
    if(active&&['/api/start','/api/export'].includes(url.pathname))throw new Error('ANOTHER_TASK_RUNNING');
    if(url.pathname==='/api/start'){const command=String(input.command);if(!['batch','produce','rank','render','resume'].includes(command))throw new Error('UNKNOWN_ACTION');let config:ProductionConfig,dir:string;if(['batch','produce'].includes(command)){config=ProductionConfigSchema.parse(input.config);dir=directory(config.output);if(!existsSync(resolve(dir,'batch.json'))){const initialized=await openBatch(config);await initialized.release();}}else{dir=directory(input.batch);config=BatchManifestSchema.parse(await readJSON(resolve(dir,'batch.json'))).config;}const configPath=resolve(dir,'production-config.json');await atomicJSON(configPath,config);await launch(dir,[command==='resume'?'produce':command,'--config',configPath,...(existsSync(resolve(dir,'batch.json'))?['--resume']:[])]);send({batch:dir});return true;}
    if(url.pathname==='/api/cancel'){const dir=directory(input.batch);if(active&&active.directory!==dir)throw new Error('ACTIVE_BATCH_DIFFERS');await atomicWrite(resolve(dir,'cancel.request'),'cancel\n');const child=active?.process;if(child){const watch=setInterval(()=>void atomicWrite(resolve(dir,'cancel.request'),'cancel\n').catch(()=>{}),100);child.once('close',()=>clearInterval(watch));}send({cancelled:true});return true;}
    if(url.pathname==='/api/export'){const template=String(input.templateId),preset=String(input.preset??'vertical-1080');if(!['arena-dark','arena-light'].includes(template)||!['vertical-1080','vertical-720'].includes(preset))throw new Error('INVALID_TEMPLATE_OR_PRESET');const dir=input.batch?directory(input.batch):await importReplay(input.files,template as 'arena-dark'|'arena-light'),batch=BatchManifestSchema.parse(await readJSON(resolve(dir,'batch.json'))),match=typeof input.match==='string'?input.match:batch.selection[0];if(!batch.tasks.some(t=>t.matchId===match&&t.manifestHash))throw new Error('UNKNOWN_MATCH');await launch(dir,['export-replay','--batch',dir,'--match',match!,'--template',template,'--preset',preset]);send({batch:dir});return true;}
    throw new Error('UNKNOWN_ACTION');
  }
  if(request.method!=='GET')throw new Error('METHOD_NOT_ALLOWED');
  if(url.pathname==='/api/bootstrap'){send({token,config:await readJSON(resolve('production.example.json'))});return true;}
  if(url.pathname==='/api/jobs'){send({token,jobs:await listJobs(artifacts)});return true;}
  const dir=directory(url.searchParams.get('batch')),batch=BatchManifestSchema.parse(await readJSON(resolve(dir,'batch.json')));
  if(url.pathname==='/api/status'){send({batch,active:active?.directory===dir,rankings:existsSync(resolve(dir,'rankings.json'))?await readJSON(resolve(dir,'rankings.json')):null});return true;}
  if(url.pathname==='/api/replay'){const id=url.searchParams.get('match'),task=batch.tasks.find(t=>t.matchId===id);if(!task?.manifestHash)throw new Error('UNKNOWN_MATCH');const matchDir=resolve(dir,'matches',task.matchId),pkg=await loadReplayPackage(matchDir);if(!pkg.frames.length){const rebuilt=rebuildPresentation(compilePhase3BContent(pkg.content),pkg.replay,pkg.hashes,pkg.manifest.runner,false);pkg.frames=rebuilt.frames;}send({package:pkg,manifestHash:fileHash(await safeRead(matchDir,'manifest.json'))});return true;}
  if(url.pathname==='/api/video'){const id=url.searchParams.get('export');if(!batch.tasks.some(t=>t.exportId===id&&t.state==='complete'))throw new Error('VIDEO_NOT_VERIFIED');response.setHeader('Content-Type','video/mp4');createReadStream(containedPath(dir,`exports/${id}/video.mp4`)).pipe(response);return true;}
  throw new Error('UNKNOWN_ENDPOINT');
}catch(error){send({error:error instanceof Error?error.message:String(error)},400);}return true;});console.log(`制作工作台：${server.url}`);return server;}
