import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {gzipSync} from 'node:zlib';
import {performance} from 'node:perf_hooks';
import {createHash} from 'node:crypto';
import {compilePhase3BContent,PACING_PROFILE_ID} from '../dist/node/content/phase3b.js';
import {UtilityRunner} from '../dist/node/runner/utility.js';
import {fighterConfig} from '../dist/node/runner/fighter.js';
import {pacingMetrics,PACING_METRICS_VERSION} from '../dist/node/analysis/pacing-metrics.js';
import {canonicalSerialize} from '../dist/node/math/canonical.js';
import {hashCanonical} from '../dist/node/math/hash.js';
import {deriveSeed} from '../dist/node/math/random.js';
const args=process.argv.slice(2),manifestPath=args.includes('--manifest')?args[args.indexOf('--manifest')+1]:'fixtures/seeds/pacing-pairs-v1.json',pilot=args.includes('--pilot'),conservative=args.includes('--conservative'),trainOnly=conservative||args.includes('--train');
const source=JSON.parse(await readFile('content/fighter-phase3b.json','utf8'));
const sourceFiles=Object.fromEntries(await Promise.all(['src/director/pacing.ts','src/ai/director-score.ts','src/ai/utility.ts','src/ai/memory.ts','src/runner/utility.ts','src/runner/observation.ts','src/replay/frame.ts','src/contracts/pacing.ts','src/contracts/ai-schema.ts','src/contracts/fighter.ts','src/sim/fighter.ts','src/analysis/pacing-metrics.ts'].map(async file=>[file,createHash('sha256').update(await readFile(file)).digest('hex')]))),sourceIdentity=hashCanonical(sourceFiles);
if(conservative){Object.assign(source.pacingProfiles[0],{version:2,noInteractionThresholdTicks:210,repeatedMissThreshold:4,readyHoldThresholdTicks:240});}
const content=compilePhase3BContent(source),manifest=JSON.parse(await readFile(manifestPath,'utf8')),{datasetHash,...body}=manifest;assert.equal(hashCanonical(body),datasetHash);assert.equal(manifest.cases.length,200);
const cases=pilot?manifest.cases.filter(c=>c.split==='train').slice(0,20):trainOnly?manifest.cases.filter(c=>c.split==='train'):manifest.cases,dir=resolve(conservative?'artifacts/phase-3b/conservative-v2':pilot?'artifacts/phase-3b/pilot':'artifacts/phase-3b'),results=[],examples={},review=[];await mkdir(resolve(dir,'records'),{recursive:true});await mkdir(resolve(dir,'review'),{recursive:true});await mkdir(resolve(dir,'examples'),{recursive:true});
const save=(path,value)=>writeFile(path,canonicalSerialize(value)+'\n');
const reviewCases=new Set(manifest.cases.filter(c=>c.sampleIndex<2).map(c=>c.caseId));
for(const item of cases){const runs={};for(const mode of ['off','pace']){const cfg=fighterConfig(content,item.seed,item.a,item.b);cfg.pacing={mode,profileId:mode==='off'?null:PACING_PROFILE_ID};const runner=new UtilityRunner(content,cfg,{trace:true}),start=performance.now(),replay=runner.run(),hostMs=performance.now()-start;assert.notEqual(replay.result.reason,'invalid',item.caseId+' '+mode);const metrics=pacingMetrics(replay,runner.frames),records=replay.directorRecords??[];
 const influences=runner.traces.flatMap(entry=>{const selected=entry.trace.candidates.find(c=>c.option.key===entry.trace.selectedKey),adjusted=entry.trace.candidates.filter(c=>c.score?.director?.applied);return adjusted.length?[{entityId:entry.entityId,tick:entry.trace.nowTick,cue:entry.trace.directorCue,selectedKey:entry.trace.selectedKey,selectedDelta:selected?.score?.director?.applied??0,adjusted:adjusted.map(c=>({key:c.option.key,Ubase:c.score.Ubase,delta:c.score.director.applied,U:c.score.Uraw}))}]:[];});
 runs[mode]={mode,hostMs,metrics,result:replay.result,inputHash:hashCanonical(replay.inputs),finalWorldHash:replay.finalWorldHash,runnerHash:runner.runnerHash(),cues:records.filter(r=>r.type==='issued'),influencedDecisions:influences.length};
 await writeFile(resolve(dir,'records',`${item.caseId}-${mode}.json.gz`),gzipSync(canonicalSerialize(replay)+'\n'));await writeFile(resolve(dir,'records',`${item.caseId}-${mode}.director.ndjson.gz`),gzipSync(records.map(r=>canonicalSerialize(r)).join('\n')+'\n'));
 for(const kind of ['engage','vary','showcase']){const influence=influences.find(v=>v.cue.kind===kind&&(kind!=='showcase'||runner.traces.find(t=>t.entityId===v.entityId&&t.trace.nowTick===v.tick)?.trace.input.cast?.slot==='ultimate'));if(influence&&!examples[kind]){examples[kind]={...item,mode,...influence};await save(resolve(dir,'examples',kind+'.json'),replay);await save(resolve(dir,'examples',kind+'.trace.json'),{config:cfg,contentHash:content.bundleHash,traces:runner.traces});}}
 if(!pilot&&reviewCases.has(item.caseId)){const pairIndex=[...reviewCases].indexOf(item.caseId)+1,firstMode=deriveSeed(2026,'pacing-review',item.caseId)%2===0?'off':'pace',side=mode===firstMode?'X':'Y',label=`pair-${String(pairIndex).padStart(2,'0')}-${side}`,file=label+'.json';await save(resolve(dir,'review',file),{schemaVersion:1,label,frames:runner.frames,events:replay.events,characters:content.source.characters,abilities:content.source.abilities,statuses:content.source.statuses,arenas:content.source.arenas});review.push({label,url:'./'+file,mode,caseId:item.caseId});}
 }
 results.push({...item,...runs});if(results.length%10===0){await save(resolve(dir,'partial.json'),{status:'running',configs:results.length,results});console.log(`Pacing pairs ${results.length}/${cases.length}`);}}
const percentile=(v,q)=>{v.sort((a,b)=>a-b);return v.length?v[Math.ceil(v.length*q)-1]:null;};
function aggregate(rows,mode){const ms=rows.map(r=>r[mode].metrics),sum=k=>ms.reduce((s,r)=>s+r[k],0),cold=ms.flatMap(m=>m.coldIntervalsTicks),gaps=ms.flatMap(m=>m.coldGapsTicks);return {matches:ms.length,invalid:rows.filter(r=>r[mode].result.reason==='invalid').length,coldIntervals:cold.length,coldMeanSeconds:cold.length?cold.reduce((a,b)=>a+b,0)/cold.length/60:null,coldP90Seconds:percentile(cold,.9)/60,allGapP90Seconds:percentile(gaps,.9)/60,longestColdP90Seconds:percentile(ms.map(m=>m.longestColdTicks),.9)/60,longestColdMaxSeconds:Math.max(...ms.map(m=>m.longestColdTicks))/60,interactionFraction:ms.reduce((s,m)=>s+m.interactionFraction*m.ticks,0)/sum('ticks'),basicCasts:sum('basicCasts'),basicMisses:sum('basicMisses'),basicMissRate:sum('basicMisses')/sum('basicCasts'),repeatedConfirmedAttackMisses:sum('repeatedConfirmedAttackMisses'),ultimateCasts:sum('ultimateCasts'),effectiveUltimates:sum('effectiveUltimates'),ultimateEffectiveRate:sum('ultimateCasts')?sum('effectiveUltimates')/sum('ultimateCasts'):null,meanDurationSeconds:sum('durationSeconds')/ms.length,durationP90Seconds:percentile(ms.map(m=>m.durationSeconds),.9),rejectedRequests:sum('rejectedRequests'),requests:sum('requests'),oneSided:ms.filter(m=>m.oneSided).length,oneSidedFraction:ms.filter(m=>m.oneSided).length/ms.length,meanDamageParticipation:ms.reduce((s,m)=>s+m.participation,0)/ms.length,hostMs:rows.reduce((s,r)=>s+r[mode].hostMs,0),cues:Object.fromEntries(['engage','vary','showcase'].map(k=>[k,rows.reduce((s,r)=>s+r[mode].cues.filter(c=>c.cue.kind===k).length,0)])),influencedDecisions:rows.reduce((s,r)=>s+r[mode].influencedDecisions,0)};}
const off=aggregate(results,'off'),pace=aggregate(results,'pace'),reduction=off.coldP90Seconds?1-pace.coldP90Seconds/off.coldP90Seconds:null;
const report={schemaVersion:1,passed:true,engineBuild:'phase3b-v1',aiVersion:'utility-v3',contentHash:content.bundleHash,profile:content.source.pacingProfiles[0],metricsVersion:PACING_METRICS_VERSION,manifestHash:datasetHash,configs:cases.length,executions:cases.length*2,pilot,trainOnly,conservative,definitions:{coldInterval:'Complete effective-interaction gaps >=180 ticks; include opening and censored match tail. Also report all gaps and per-match longest gaps.',interaction:'Cumulative actual HP damage >=1, positive prevention, reflection or barrier dissipation; 60-tick coverage.',oneSided:'Weaker actual damage contribution / total damage <0.20 (zero total counts one-sided).',repeat:'Third and later confirmed ineffective basic/projectile use in 180 ticks, reset by effective use; unexpired effects censored.',cost:'Node elapsed simulation with frames+decision trace enabled; excludes metrics, serialization and IO.'},off,pace,train:{off:aggregate(results.filter(r=>r.split==='train'),'off'),pace:aggregate(results.filter(r=>r.split==='train'),'pace')},...(pilot||trainOnly?{}:{holdout:{off:aggregate(results.filter(r=>r.split==='holdout'),'off'),pace:aggregate(results.filter(r=>r.split==='holdout'),'pace')}}),effect:{coldP90Reduction:reduction,target:.2,targetMet:reduction!==null&&reduction>=.2,invalidRequestsNotWorse:pace.rejectedRequests<=off.rejectedRequests,oneSidedNotWorse:pace.oneSidedFraction<=off.oneSidedFraction},examples,results};
report.sourceIdentity=sourceIdentity;report.sourceFiles=sourceFiles;
await save(resolve(dir,'evaluation.json'),report);
if(!pilot){review.sort((a,b)=>a.label.localeCompare(b.label));await save(resolve(dir,'review','private-key.json'),{review,manifestHash:datasetHash,contentHash:content.bundleHash});await save(resolve(dir,'review','index.json'),{schemaVersion:1,reviewId:'phase3b-pacing-v1-'+hashCanonical(review).slice(0,12),title:'节奏导演成对盲评',paired:true,status:'pending-human-review',entries:review.map(({label,url})=>({label,url}))});}
console.log(JSON.stringify({configs:cases.length,off,pace,effect:report.effect,examples},null,2));
