import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {readFile,mkdir,writeFile,unlink} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {openBatch,simulateBatch,rankBatch} from '../dist/node/jobs/batch.js';
import {loadReplayPackage,saveReplayPackage} from '../dist/node/jobs/replay-store.js';
import {atomicWrite,atomicJSON,fileHash} from '../dist/node/jobs/files.js';
import {acquireJobLock} from '../dist/node/jobs/lock.js';
import {compilePhase3BContent} from '../dist/node/content/phase3b.js';
import {fighterConfig} from '../dist/node/runner/fighter.js';
import {recordMatch,rebuildPresentation} from '../dist/node/runner/record-match.js';
import {analyzeMatch} from '../dist/node/analysis/interesting.js';
import {hashCanonical} from '../dist/node/math/hash.js';
const run=resolve('artifacts/phase-4',`correctness-${Date.now()}`);await mkdir(run,{recursive:true});
const characters=['standard','rubber','iron','mirror'],matchups=characters.flatMap((a,i)=>characters.slice(i).map(b=>({a,b}))),base={schemaVersion:1,id:'phase4-worker-fixture',seed:20261003,matchups,countPerMatchup:2,workers:1,top:10,pacing:'off',preset:'vertical-720',templateId:'arena-dark',keepFrames:true,fullCheckpoints:true,maxTicks:3600};
async function execute(config,options={}){const opened=await openBatch(config,options);try{await simulateBatch(opened.context);const ranking=await rankBatch(opened.context);return {batch:structuredClone(opened.context.batch),ranking};}finally{await opened.release();}}
const one=await execute({...base,output:resolve(run,'worker1')}),four=await execute({...base,output:resolve(run,'worker4'),workers:4});const comparisons=[];
assert.deepEqual(one.ranking,four.ranking);for(let i=0;i<one.batch.tasks.length;i++){const a=one.batch.tasks[i],b=four.batch.tasks[i];assert.deepEqual(a.config,b.config);const pa=await loadReplayPackage(resolve(run,'worker1/matches',a.matchId)),pb=await loadReplayPackage(resolve(run,'worker4/matches',b.matchId));assert.deepEqual(pa.replay,pb.replay);assert.deepEqual(pa.hashes,pb.hashes);assert.deepEqual(pa.analysis,pb.analysis);assert.equal(a.manifestHash,b.manifestHash);comparisons.push({matchId:a.matchId,seed:a.config.seed,inputHash:hashCanonical(pa.replay.inputs),eventHash:hashCanonical(pa.replay.events),finalWorldHash:pa.replay.finalWorldHash,manifestHash:a.manifestHash});}
const tiny={...base,id:'phase4-retry-fixture',matchups:[{a:'iron',b:'iron'}],countPerMatchup:1,workers:1,top:1},control=await execute({...tiny,output:resolve(run,'retry-control')}),crashed=await execute({...tiny,output:resolve(run,'retry-crash')},{fault:'worker-crash'});assert.equal(crashed.batch.tasks[0].attempts,2);assert.equal(crashed.batch.tasks[0].manifestHash,control.batch.tasks[0].manifestHash);assert.equal(crashed.batch.failures[0].errorCode,'WORKER_EXIT_17');assert.deepEqual(crashed.batch.tasks[0].config,control.batch.tasks[0].config);
const failed=await execute({...tiny,output:resolve(run,'twice-failed')},{fault:'simulation'});assert.equal(failed.batch.tasks[0].attempts,2);assert.equal(failed.batch.tasks[0].manifestHash,null);assert.equal(failed.batch.failures.length,2);const retryFailed=await execute({...tiny,output:resolve(run,'twice-failed')},{resume:true});assert.equal(retryFailed.batch.tasks[0].attempts,2);assert.equal(retryFailed.batch.failures.length,2);
const cancelConfig={...base,output:resolve(run,'cancelled')},opened=await openBatch(cancelConfig);await atomicWrite(resolve(opened.context.directory,'cancel.request'),'cancel');try{await simulateBatch(opened.context);assert.equal(opened.context.batch.status,'cancelled');assert(opened.context.batch.tasks.every(t=>t.state==='pending'&&t.attempts===0));}finally{await opened.release();}const resumed=await execute(cancelConfig,{resume:true});assert.equal(resumed.batch.tasks.length,20);assert(resumed.batch.tasks.every(t=>t.manifestHash&&t.attempts===1));
const lockDir=resolve(run,'lock');const release=await acquireJobLock(lockDir);await assert.rejects(()=>acquireJobLock(lockDir),/JOB_LOCKED/);await release();const lockModule=new URL('../dist/node/jobs/lock.js',import.meta.url).href,stale=spawnSync(process.execPath,['--input-type=module','-e',`import {acquireJobLock} from ${JSON.stringify(lockModule)};await acquireJobLock(${JSON.stringify(lockDir)});`],{encoding:'utf8',windowsHide:true});assert.equal(stale.status,0,stale.stderr);await (await acquireJobLock(lockDir))();await writeFile(resolve(lockDir,'.job.lock'),'bad');await assert.rejects(()=>acquireJobLock(lockDir),/LOCK_CORRUPT/);await unlink(resolve(lockDir,'.job.lock'));
const content=compilePhase3BContent(JSON.parse(await readFile('content/fighter-phase3b.json','utf8'))),runner={kinds:['utility','utility'],settings:{noise:true,randomChoice:true,memory:true}},director=[];
for(const mode of ['off','observe','pace']){const config=fighterConfig(content,611974910,'iron','iron');config.matchId='phase4-director-'+mode;config.pacing={mode,profileId:mode==='off'?null:'gentle-v1'};const data=recordMatch(content,config,runner,true),dir=resolve(run,'director',mode);await saveReplayPackage(dir,{...data,content,runner,analysis:analyzeMatch(data.replay,data.frames),toolchainId:'export-win-x64-ffmpeg9.0.2-chromium153-v1'});const loaded=await loadReplayPackage(dir);assert.deepEqual(loaded.replay,data.replay);assert.deepEqual(rebuildPresentation(content,loaded.replay,loaded.hashes,runner,true).checkpoints,loaded.checkpoints);assert.equal(loaded.replay.directorRecords.length===0,mode==='off');assert.equal(loaded.checkpoints.every(cp=>cp.pacingDirector===null),mode==='off');director.push({mode,ticks:loaded.manifest.durationTicks,records:loaded.replay.directorRecords.length,checkpoints:loaded.checkpoints.length});}
const sampleDir=resolve(run,'director','pace'),original=await readFile(resolve(sampleDir,'inputs.ndjson.gz'));await writeFile(resolve(sampleDir,'inputs.ndjson.gz'),original.subarray(0,20));await assert.rejects(()=>loadReplayPackage(sampleDir),/HASH_MISMATCH/);await atomicWrite(resolve(sampleDir,'inputs.ndjson.gz'),original);const originalManifest=await readFile(resolve(sampleDir,'manifest.json'));const bad=JSON.parse(originalManifest);bad.replaySchemaVersion=999;await atomicJSON(resolve(sampleDir,'manifest.json'),bad);await assert.rejects(()=>loadReplayPackage(sampleDir));await atomicWrite(resolve(sampleDir,'manifest.json'),originalManifest);await loadReplayPackage(sampleDir);
const output={passed:true,run,workers1and4:{matches:20,matchups:10,allInputEventWorldRunnerResultAndRankEqual:true,comparisons},workerCrash:{realExitCode:17,attempts:2,sameSeedConfigAndManifest:true,diagnostic:crashed.batch.failures[0]},twiceFailed:{attempts:2,noThirdRetry:true},cancellation:{unfinishedPending:true,resumed:20},windowsLocks:{activeRefused:true,deadProcessRecovered:true,corruptRefused:true},director,corruption:{truncatedInputRejected:true,unknownSchemaRejected:true}};await atomicJSON(resolve('artifacts/phase-4/correctness.json'),output);console.log('Phase4 correctness passed: 20 worker pairs, real crash/retry, cancellation, Windows locks, three director packages and corruption rejection.');
