import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {resolve} from 'node:path';
import {compileUtilityContent} from '../dist/node/content/utility.js';
import {UtilityRunner} from '../dist/node/runner/utility.js';
import {fighterConfig} from '../dist/node/runner/fighter.js';
import {FighterSimulation} from '../dist/node/sim/fighter.js';
import {fighterWorldHash} from '../dist/node/sim/fighter-state.js';
import {replayInputs} from '../dist/node/runner/input-replay.js';
import {canonicalSerialize} from '../dist/node/math/canonical.js';
import {hashCanonical} from '../dist/node/math/hash.js';
import {deriveSeed} from '../dist/node/math/random.js';
import {behaviorMetrics,wilson} from '../dist/node/analysis/ai-metrics.js';
const dir=resolve('artifacts/phase-2');await mkdir(resolve(dir,'replays'),{recursive:true});
const source=JSON.parse(await readFile('content/fighter-phase2.json','utf8')),content=compileUtilityContent(source),manifest=JSON.parse(await readFile('fixtures/seeds/dev-smoke.json','utf8')),baseline=JSON.parse(await readFile('fixtures/seeds/ai-baseline-v1.json','utf8'));
const save=async(path,data)=>writeFile(path,canonicalSerialize(data)+'\n');
const results=[],coverage=new Set();let representative=null;
for(const item of manifest.cases){const config=fighterConfig(content,item.seed,item.a,item.b),a=new UtilityRunner(content,config,{trace:true,recordFrames:false}),b=new UtilityRunner(content,config,{trace:false,recordFrames:false}),hashes=[],runnerHashes=[],resume=new Map();
 while(!a.sim.snapshot().result){a.step();hashes.push(fighterWorldHash(a.sim.snapshot()));if(a.sim.snapshot().tick%60===0)runnerHashes.push(a.runnerHash());if([120,240].includes(a.sim.snapshot().tick))resume.set(a.sim.snapshot().tick,a.snapshot(true));}
 const ra=a.replay();assert.notEqual(ra.result.reason,'invalid');
 const otherHashes=[],otherRunnerHashes=[];while(!b.sim.snapshot().result){b.step();otherHashes.push(fighterWorldHash(b.sim.snapshot()));if(b.sim.snapshot().tick%60===0)otherRunnerHashes.push(b.runnerHash());}
 assert.deepEqual(hashes,otherHashes);assert.deepEqual(runnerHashes,otherRunnerHashes);assert.equal(canonicalSerialize(ra),canonicalSerialize(b.replay()));assert.equal(a.runnerHash(),b.runnerHash());
 const replaySim=new FighterSimulation(content,config,undefined,'phase2-v1'),inputHashes=[];for(const entry of ra.inputs){replaySim.step(entry.intents);inputHashes.push(fighterWorldHash(replaySim.snapshot()));}assert.deepEqual(inputHashes,hashes);replayInputs(ra,false);
 if(item.caseId==='standard-vs-standard-0'){for(const [tick,cp] of resume){const r=new UtilityRunner(content,config,{recordFrames:false});r.restore(JSON.parse(JSON.stringify(cp)));while(!r.sim.snapshot().result){r.step();assert.equal(fighterWorldHash(r.sim.snapshot()),hashes[r.sim.snapshot().tick-1]);assert.deepEqual(r.inputs.at(-1),ra.inputs[r.sim.snapshot().tick-1]);}assert.equal(r.runnerHash(),a.runnerHash());assert.deepEqual(r.replay(),ra);}const r=new UtilityRunner(content,config,{recordFrames:false});for(let t=0;t<ra.inputs.length-1;t++)r.step();const near=new UtilityRunner(content,config,{recordFrames:false});near.restore(JSON.parse(JSON.stringify(r.snapshot(true))));near.step();assert.deepEqual(near.replay(),ra);assert.equal(near.runnerHash(),a.runnerHash());}
 for(const e of ra.events)if(e.type==='CastAccepted')coverage.add(e.payload.abilityId);
 const hit=new Set(ra.events.filter(e=>e.type==='DamageResolved').map(e=>e.payload.castId)),miss=ra.events.find(e=>e.type==='CastAccepted'&&!hit.has(e.payload.castId)&&content.source.abilities.find(a=>a.id===e.payload.abilityId).ai.purpose==='damage');
 if(!representative&&miss){const trace=a.traces.find(t=>t.entityId===miss.sourceId&&t.trace.requestId===miss.payload.requestId);assert(trace);representative={caseId:item.caseId,seed:item.seed,tick:miss.tick,castId:miss.payload.castId,requestId:miss.payload.requestId,abilityId:miss.payload.abilityId,trace};await save(resolve(dir,'miss-trace.json'),{contentHash:content.bundleHash,config,traces:a.traces});}
 await save(resolve(dir,'replays',`${item.caseId}.json`),ra);results.push({caseId:item.caseId,seed:item.seed,ticks:ra.inputs.length,result:ra.result,finalWorldHash:ra.finalWorldHash,worldSequenceHash:hashCanonical(hashes),runnerSequenceHash:hashCanonical(runnerHashes),finalRunnerHash:a.runnerHash(),decisions:a.traces.length,emergencies:a.traces.filter(t=>t.trace.emergency).length,stuckDecisions:a.traces.filter(t=>t.trace.stuck).length});console.log(`Utility smoke ${results.length}/30: ${item.caseId} ${ra.result.reason} ${ra.inputs.length} ticks`);
}
assert.equal(results.length,30);assert(representative);assert(coverage.has('rubber-dash'));assert(coverage.has('standard-volley'));
const processes=['process-a.json','process-b.json'];for(const name of processes){const p=spawnSync(process.execPath,['dist/node/cli/simulate.js','--ai','utility','--a','standard','--b','rubber','--seed','17','--output',resolve(dir,name),'--checkpoint-at','240','--checkpoint',resolve(dir,`${name}.checkpoint.json`)],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);}assert.equal(await readFile(resolve(dir,processes[0]),'utf8'),await readFile(resolve(dir,processes[1]),'utf8'));
const restored=spawnSync(process.execPath,['dist/node/cli/simulate.js','--resume',resolve(dir,`${processes[0]}.checkpoint.json`),'--output',resolve(dir,'process-resumed.json')],{encoding:'utf8'});assert.equal(restored.status,0,restored.stderr);assert.equal(await readFile(resolve(dir,processes[0]),'utf8'),await readFile(resolve(dir,'process-resumed.json'),'utf8'));
const selected=baseline.cases.filter(c=>['standard','rubber'].includes(c.a)&&(c.sampleIndex<5||c.sampleIndex>=25&&c.sampleIndex<30));assert.equal(selected.length,80);const baselineResults=[];
for(const item of selected){const cfg=fighterConfig(content,item.seed,item.a,item.b),utilityIndex=item.side===0?0:1;cfg.participants[utilityIndex].participantId='utility';cfg.participants[1-utilityIndex].participantId='baseline';const kinds=utilityIndex===0?['utility',item.baseline]:[item.baseline,'utility'],r=new UtilityRunner(content,cfg,{kinds,recordFrames:true}),start=performance.now(),replay=r.run(),elapsedMs=performance.now()-start;if(replay.result.reason==='invalid'){await save(resolve(dir,'baseline-failure.json'),{item,content:content.source,checkpoint:r.snapshot(true)});throw new Error('Invalid baseline '+item.caseId);}const metrics=behaviorMetrics(replay,r.frames,utilityIndex+1);baselineResults.push({...item,winner:replay.result.winnerParticipantId,reason:replay.result.reason,metrics,elapsedMs});if(baselineResults.length%10===0)console.log(`Initial baseline ${baselineResults.length}/80`);}
const aggregates=[];for(const character of ['standard','rubber'])for(const opponent of ['rush','ranged'])for(const split of ['train','holdout']){const rows=baselineResults.filter(r=>r.a===character&&r.baseline===opponent&&r.split===split),wins=rows.filter(r=>r.winner==='utility').length,losses=rows.filter(r=>r.winner==='baseline').length;assert.equal(rows.length,10);const basics=rows.reduce((s,r)=>s+r.metrics.basicCasts,0),misses=rows.reduce((s,r)=>s+r.metrics.basicMisses,0),requests=rows.reduce((s,r)=>s+r.metrics.requests,0),rejected=rows.reduce((s,r)=>s+r.metrics.rejectedRequests,0);aggregates.push({character,baseline:opponent,split,n:rows.length,wins,losses,draws:rows.length-wins-losses,winRate:wins/rows.length,wilson95:wilson(wins,rows.length),basicMissRate:basics?misses/basics:null,invalidRequestRate:requests?rejected/requests:null,meanFirstInteractionSeconds:rows.reduce((s,r)=>s+(r.metrics.firstInteractionSeconds??60),0)/rows.length,longWallStallMatches:rows.filter(r=>r.metrics.longWallStall).length});}
await save(resolve(dir,'baseline.json'),{scope:'Phase 2 initial two-character subset; full frozen 800 matches belong to Phase 3',parentManifestHash:baseline.datasetHash,subsetHash:hashCanonical(selected),n:80,train:40,holdout:40,aggregates,results:baselineResults});
// H2 same character and identical reaction/noise/decision budget; only preference weights differ.
const reviewSource=structuredClone(source);for(const id of ['pressure','counter']){const p=reviewSource.profiles.find(p=>p.id===id);p.reactionDelayTicks=9;p.positionNoisePx=6;p.velocityNoisePxPerSecond=18;p.decisionIntervalTicks=6;p.nearBestBand=.8;}
const reviewContent=compileUtilityContent(reviewSource),reviewDir=resolve(dir,'h2');await mkdir(reviewDir,{recursive:true});const privateKey=[],reviewMetrics=[];
const entries=[];for(let i=0;i<10;i++)for(const id of ['pressure','counter'])entries.push({index:i,profile:id,seed:deriveSeed(20261002,'h2-style',i)});entries.sort((a,b)=>deriveSeed(909,'order',a.index,a.profile)-deriveSeed(909,'order',b.index,b.profile));
for(let i=0;i<entries.length;i++){const item=entries[i],character=item.index<5?'standard':'rubber',cfg=fighterConfig(reviewContent,item.seed,character,character);cfg.participants[0].profileId=item.profile;cfg.participants[1].profileId='balanced';cfg.matchId=`review-${String(i+1).padStart(2,'0')}`;const r=new UtilityRunner(reviewContent,cfg,{kinds:['utility','rush']}),replay=r.run();assert.notEqual(replay.result.reason,'invalid');const label=cfg.matchId;await save(resolve(reviewDir,`${label}.json`),{schemaVersion:1,label,frames:r.frames,events:replay.events,characters:reviewContent.source.characters,abilities:reviewContent.source.abilities,arenas:reviewContent.source.arenas});privateKey.push({label,...item,finalWorldHash:replay.finalWorldHash});reviewMetrics.push({label,profile:item.profile,seed:item.seed,metrics:behaviorMetrics(replay,r.frames,1)});}
await save(resolve(reviewDir,'index.json'),{schemaVersion:1,title:'H2 两角色观感盲评',status:'pending-human-review',entries:privateKey.map(k=>({label:k.label,url:`./${k.label}.json`}))});await save(resolve(reviewDir,'private-key.json'),{sameReactionDelayTicks:9,samePositionNoisePx:6,sameVelocityNoisePxPerSecond:18,key:privateKey,metrics:reviewMetrics});
const timed=new UtilityRunner(content,fighterConfig(content,17),{trace:true,recordFrames:false}),durations=[];for(const controller of timed.controllers){const update=controller.update.bind(controller);controller.update=o=>{const start=performance.now(),input=update(o),ms=performance.now()-start;if(controller.lastTrace)durations.push(ms);return input;};}timed.run();durations.sort((a,b)=>a-b);
await save(resolve(dir,'smoke.json'),{passed:true,engineBuild:'phase2-v1',aiVersion:'utility-v1',node:process.version,contentHash:content.bundleHash,datasetHash:manifest.datasetHash,configs:30,repeatExecutions:60,inputReplays:30,perTickWorldHashEqual:true,runnerHashAt60Equal:true,traceOnOffEqual:true,fullCheckpointTicks:[120,240,'actual-end-minus-1'],independentProcessesEqual:true,cliResumeByteEqual:true,coveredAbilities:[...coverage].sort(),representative,baselineMatches:80,predictionTiming:{seed:17,samples:durations.length,includes:'memory, prediction, selection and trace construction per actual decision; host timing excluded from state',meanMs:durations.reduce((a,b)=>a+b,0)/durations.length,p95Ms:durations[Math.floor(durations.length*.95)]},h2:{status:'pending-human-review',matches:20,pressure:10,counter:10,index:'artifacts/phase-2/h2/index.json'},results});console.log('Phase 2 smoke, 80 initial baselines, and 20 H2 blinded matches passed. H2 remains pending human review.');
