import type { BatchManifest } from '../contracts/production.js';
import './production.css';
const el=<T extends HTMLElement>(id:string)=>document.querySelector<T>('#'+id)!;
const jobs=el<HTMLSelectElement>('jobs'),status=el('status');let token='';
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
async function api(path:string,body?:unknown){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Production-Token':token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;}
async function refresh(){const list=await api('jobs');token=list.token;const previous=jobs.value;jobs.innerHTML=list.jobs.map((j:{path:string;batchId:string;status:string})=>`<option value="${escape(j.path)}">${escape(j.batchId)} · ${j.status}</option>`).join('');if([...jobs.options].some(o=>o.value===previous))jobs.value=previous;}
async function show(){if(!jobs.value){status.textContent='可以开始新批次';return;}const result=await api('status?batch='+encodeURIComponent(jobs.value)),batch=result.batch as BatchManifest;status.textContent=result.active?'任务正在运行':'批次状态：'+batch.status;el('summary').textContent=`${batch.tasks.length} 场 · ${batch.selection.length} 场入选 · ${batch.tasks.filter(t=>t.state==='complete').length} 条视频完成`;
  el('tasks').innerHTML=batch.tasks.map(t=>`<tr><td>${t.config.participants.map(p=>escape(p.characterId)).join(' × ')}<br><small>${t.config.seed} · ${t.matchId.slice(-8)}</small></td><td>${t.score?.toFixed(2)??'—'}<br>${escape(t.selectionReason??'等待模拟')}</td><td>${t.state}${t.failures.length?' · '+t.failures.length+' 次故障':''}</td><td><progress max="${t.totalFrames||1}" value="${t.framesComplete}"></progress><br>${t.framesComplete}/${t.totalFrames||'—'}</td><td>${t.manifestHash?`<a href="/replay.html?batch=${encodeURIComponent(jobs.value)}&match=${t.matchId}">回放</a>`:''}${t.state==='complete'?` · <a href="/api/video?batch=${encodeURIComponent(jobs.value)}&export=${t.exportId}" target="_blank">视频</a>`:''}</td></tr>`).join('');el('details').textContent=JSON.stringify({rankings:result.rankings,failures:batch.failures},null,2);
}
for(const command of ['batch','produce','rank','render','resume'])el(command).onclick=()=>void (async()=>{const config=['batch','produce'].includes(command)?JSON.parse(el<HTMLTextAreaElement>('config').value):undefined;const result=await api('start',{command,config,batch:jobs.value});status.textContent='任务已启动';await refresh();jobs.value=result.batch;await show();})().catch(error=>{status.textContent=String(error);});
el('cancel').onclick=()=>void api('cancel',{batch:jobs.value}).then(()=>{status.textContent='正在完成当前文件写入并取消…';}).catch(error=>{status.textContent=String(error);});el('refresh').onclick=()=>void refresh().then(show);jobs.onchange=()=>void show();
try{const bootstrap=await api('bootstrap');token=bootstrap.token;el<HTMLTextAreaElement>('config').value=JSON.stringify(bootstrap.config,null,2);await refresh();await show();setInterval(()=>void show().catch(error=>{status.textContent=String(error);}),1000);Object.assign(globalThis,{productionReady:true});}catch(error){status.textContent=`${error}\n请运行 npm run studio，使用本地制作服务打开此页面。`;}
