import { ReplayManifestSchema, type ReplayPackage, type ReplayManifest } from '../contracts/production.js';
import { decodeProductionFiles } from '../replay/package.js';
import { VideoRenderer } from '../render/renderer.js';
import { createRenderJob } from '../render/timeline.js';
import { hashCanonical } from '../math/hash.js';
import { AUDIO_ASSETS_VERSION, SOUND_SPECS } from '../render/audio.js';
import './production.css';
const el=<T extends HTMLElement>(id:string)=>document.querySelector<T>('#'+id)!,seek=el<HTMLInputElement>('seek'),template=el<HTMLSelectElement>('template'),status=el('status'),canvas=el<HTMLCanvasElement>('video');let pkg:ReplayPackage|null=null,renderer:VideoRenderer,playing=false,last=0,manifestHash='',token='',importFiles:{path:string;base64:string}[]=[];
const font=new FontFace('ExportSans','url(/fonts/NotoSansSC-Regular.otf)');await font.load();document.fonts.add(font);await document.fonts.ready;
const params=new URLSearchParams(location.search),batch=params.get('batch'),match=params.get('match');
function show(){if(!pkg)return;renderer.draw(Number(seek.value));el('time').textContent=`${(Number(seek.value)/60).toFixed(2)} / ${(pkg.manifest.durationTicks/60).toFixed(2)} 秒`;}
function restyle(){if(!pkg)return;const job=createRenderJob(pkg.manifest,manifestHash,{preset:'vertical-720',templateId:template.value as 'arena-dark'|'arena-light',fontHash:'faa6c9df652116dde789d351359f3d7e5d2285a2b2a1f04a2d7244df706d5ea9',audioAssetsHash:hashCanonical({version:AUDIO_ASSETS_VERSION,specs:SOUND_SPECS}),keepFrames:true});renderer=new VideoRenderer(canvas.getContext('2d')!,{manifest:pkg.manifest,content:pkg.content,frames:pkg.frames,events:pkg.replay.events,job});show();}
function loaded(value:ReplayPackage){if(!value.frames.length)throw new Error('此包仅保存输入。请在原版本制作服务中重建呈现轨道后再载入。');pkg=value;seek.max=String(pkg.manifest.durationTicks);seek.value='0';seek.disabled=false;el<HTMLButtonElement>('play').disabled=false;el<HTMLButtonElement>('export').disabled=false;el('config').textContent=JSON.stringify({manifest:pkg.manifest,originalConfig:pkg.manifest.config},null,2);el('analysis').textContent=JSON.stringify(pkg.analysis,null,2);el('score').textContent=`评分 ${pkg.analysis.score.toFixed(2)} · ${pkg.analysis.exchanges.length} 段有效交锋 · ${pkg.analysis.eligible?'可入选':pkg.analysis.rejectionReasons.join('、')}`;el('exchanges').replaceChildren(...pkg.analysis.exchanges.map(exchange=>{const button=document.createElement('button');button.textContent=`交锋 ${exchange.id} · ${(exchange.startTick/60).toFixed(1)}s`;button.onclick=()=>{seek.value=String(exchange.startTick+1);show();};return button;}));el('events').replaceChildren(...pkg.replay.events.filter(e=>['CastAccepted','DamageResolved','ProjectileReflected','EntityDied'].includes(e.type)).map(event=>{const button=document.createElement('button');button.textContent=`${(event.tick/60).toFixed(2)}s · ${event.type} · #${event.seq}`;button.onclick=()=>{seek.value=String(event.tick+1);show();};return button;}));status.textContent='回放校验通过 · 使用包内保存内容';restyle();Object.assign(globalThis,{replayReady:true});}
const digest=async(bytes:Uint8Array<ArrayBuffer>)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');
el<HTMLInputElement>('files').onchange=()=>void (async()=>{playing=false;const files=Array.from(el<HTMLInputElement>('files').files??[]),manifestFile=files.find(f=>f.name==='manifest.json');if(!manifestFile)throw new Error('缺少 manifest.json');const prefix=manifestFile.webkitRelativePath.slice(0,-'manifest.json'.length),manifestBytes=new Uint8Array(await manifestFile.arrayBuffer()),manifest=ReplayManifestSchema.parse(JSON.parse(new TextDecoder().decode(manifestBytes))),texts=new Map<ReplayManifest['files'][number]['role'],string>();manifestHash=await digest(manifestBytes);importFiles=[];
  const encode=(bytes:Uint8Array)=>{let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary);};importFiles.push({path:'manifest.json',base64:encode(manifestBytes)});
  for(const entry of manifest.files){const file=files.find(f=>f.webkitRelativePath===prefix+entry.path);if(!file)throw new Error('缺少文件 '+entry.path);const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length!==entry.bytes||await digest(bytes)!==entry.sha256)throw new Error('文件校验失败 '+entry.path);importFiles.push({path:entry.path,base64:encode(bytes)});const raw=entry.path.endsWith('.gz')?await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text():new TextDecoder().decode(bytes);if(raw.length>512*1024*1024)throw new Error('展开文件超出预算');texts.set(entry.role,raw);}loaded(decodeProductionFiles(manifest,texts));})().catch(error=>{status.textContent=String(error);pkg=null;});
seek.oninput=show;template.onchange=restyle;el('play').onclick=()=>{playing=!playing;last=0;el('play').textContent=playing?'暂停':'播放';};function animate(now:number){if(playing&&pkg){if(last)seek.value=String(Math.min(pkg.manifest.durationTicks,Number(seek.value)+(now-last)*.06));show();if(Number(seek.value)>=pkg.manifest.durationTicks){playing=false;el('play').textContent='播放';}}last=now;requestAnimationFrame(animate);}requestAnimationFrame(animate);
el('export').onclick=()=>void (async()=>{const response=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json','X-Production-Token':token},body:JSON.stringify({batch,match,templateId:template.value,preset:el<HTMLSelectElement>('preset').value,files:importFiles})}),value=await response.json();if(!response.ok)throw new Error(value.error);status.textContent='视频导出任务已启动，请在制作工作台查看进度。';})().catch(error=>{status.textContent=String(error);});
try{const bootstrap=await fetch('/api/bootstrap').then(r=>r.json());token=bootstrap.token;if(batch&&match){const response=await fetch('/api/replay?batch='+encodeURIComponent(batch)+'&match='+encodeURIComponent(match));const value=await response.json();if(!response.ok)throw new Error(value.error);manifestHash=value.manifestHash;loaded(value.package);}}catch(error){if(batch&&match)status.textContent=String(error);}
